### ISSUE TITLE
W2509 should be checked for AWS::EC2::VPNConnectionRoute

### ISSUE THREAD

**Issue by adamchainz** [aws-cloudformation/cfn-python-lint#1000]
*cfn-lint version: (`cfn-lint --version`)* 0.21.4 but it looks like it exists on master too

*Description of issue.*

The `DestinationCidrBlock` property of `AWS::EC2::VPNConnectionRoute` is also a CIDR so should probably be used in this rule to ensure all CIDR params have an `AllowedPattern`

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by kddejong** [comment]
This is released.
