### ISSUE TITLE
E3001 Invalid or unsupported Type AWS::SageMaker::CodeRepository

### ISSUE THREAD

**Issue by archgroove** [aws-cloudformation/cfn-python-lint#1005]
*cfn-lint version: (`cfn-lint --version`)*

cfn-lint 0.22.1

*Description of issue.*

AWS::SageMaker::CodeRepository is not recognised by cfn-lint

My template gives this error:

E3001 Invalid or unsupported Type AWS::SageMaker::CodeRepository for resource NotebookCodeRepository in us-east-1

```NotebookCodeRepository:
        Type: AWS::SageMaker::CodeRepository
        Properties:
          CodeRepositoryName: my_repo_name
          GitConfig:
            Branch: develop
            RepositoryUrl: a_git_repo
            SecretArn: a_secret_arn
   NotebookInstance:
        Type: AWS::SageMaker::NotebookInstance
        Properties:
          DefaultCodeRepository: NotebookCodeRepository
          DirectInternetAccess: Enabled
          InstanceType: ml.t2.medium
          LifecycleConfigName: NotebookLifecycleConfig
          NotebookInstanceName: NotebookInstance
          RoleArn: a_role_arn
          RootAccess: Disabled
          SecurityGroupIds:
            - a_security_group_id
          SubnetId: a_subnet_id
          Tags:
            -
              Key: NotebookInstance
          VolumeSizeInGB: 5
```

*AWS CloudFormation Docs*

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-coderepository.html

**Comment by kddejong** [comment]
This looks like this doesn't exist in any CloudFormation spec file that is provided.  So we would have to manually patch this in.

**Comment by kddejong** [comment]
Released and available.
