### ISSUE TITLE
Add option to force specific rules to be evaluated

### ISSUE THREAD

**Issue by jonathanmorley** [aws-cloudformation/cfn-python-lint#1007]
We are trying to use cfn-lint to enforce certain template patterns across the organization.

Currently users can opt-out of certain rules with Metadata in their templates (which they control).

We would like to be able to provide a list of rules which are forced to be run, and do not respect the Metadata-exclusions.

**Comment by chuckmeyer** [comment]
Hi Jonathan, 

The current scope of cfn-lint is as a validation tool, not a governance tool. Other tools like cfn-nag may be better for this function.  I like to think of cfn-lint as "can I deploy this?" and cfn-nag as "should I deploy this?".

We may add a governance mode in the future, so we'll keep this in our backlog as an enhancement (feel free to dig in if you have a solution!), but I just wanted to give you the current state of the tool and the ecosystem.

**Comment by atkinsonm** [comment]
@patmyron it looks like this was closed by #1243
