### ISSUE TITLE
Invalid GetAtt with LambdaFunctionARN

### ISSUE THREAD

**Issue by iDVB** [aws-cloudformation/cfn-python-lint#1012]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint v0.22.0

*Description of issue.*
Linting seems to not like me using...
`LambdaFunctionARN: !Ref FunctionLogicalName.Version`

**Comment by kddejong** [comment]
What type of resource is `OriginRequestProxyLambdaFunction` and `OriginResponseLambdaFunction`?   I'm guessing its `AWS::Lambda::Version`.  Which if that is the case should this be a Ref and not a GetAtt?

Also, I'm guessing this template works?  I should be able to get a fix in but want to make sure I'm looking for the right thing.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html#aws-resource-lambda-version-return-values

**Comment by iDVB** [comment]
Sorry! My bad... 
the resources type is `AWS::Serverless::Function`
and yes its supposed to be `!Ref` not GetAtt.... but it still doesn't work in the linter... but does work in CFN.

This works with serverless transform.
https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/lambda_edge

**Comment by kddejong** [comment]
Yea, absolutely fair. I kind of figured either way it wasn't going to work but wanted to make sure I put the right fix in.  I'll get on it and get it working.  Thanks for reporting this.

**Comment by kddejong** [comment]
Got it.  That is a weird syntax `!Ref FunctionLogicalName.Version` so must be related to what SAM is doing for you and how it transforms that.  It sounds like this is good close now?

**Comment by iDVB** [comment]
Yup, linter is fine with it.
