### ISSUE TITLE
Getting  E3002  Invalid Property Resources Tags

### ISSUE THREAD

**Issue by kirubel** [aws-cloudformation/cfn-python-lint#1015]
*cfn-lint version: (`cfn-lint --version`)*
current latest
*Description of issue.*
We started getting  E3002 Invalid Property Resources/.../Properties/Tags
for several resources.  These are resources that recently started supporting Tags, mainly IAM roles.  The error was not present last week when we were actually able to apply Tags to IAM roles that now started supporting tags.
We had to ignore rule check for E3002 for now to overcome this issue

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by kddejong** [comment]
@kirubel checking with some internal folks to see what and why this may have changed.  We get the spec from internal resources and I think there were a few issues with the IAM tags in particular.  Are you see this issue with anything other than IAM?

**Comment by kddejong** [comment]
Looks this is working across most areas I've tested it and isn't included in the CloudFormation spec.   I'll create a patch to patch the CloudFormation spec to cover for IAM Role and User.  Do you know what other types are failing?  I can get that cleaned up as well.

**Comment by kirubel** [comment]
Sorry for getting back to you late.  I went back to check the error logs and it appears all the issues reported were related to IAM roles.  Thank you very much for your follow up and fix! Much appreciated!

**Comment by kddejong** [comment]
Code is in for this and we it will be covered in the next release.

**Comment by kirubel** [comment]
Awesome! Thank you!

**Comment by Nathan846** [comment]
Is there an update for this issue? I am still having a lint issue with fn::transform.
