### ISSUE TITLE
[Feature request] cfn-lint --regions *

### ISSUE THREAD

**Issue by PatMyron** [aws-cloudformation/cfn-python-lint#1022]
This would currently be equivalent to something like this, but the list would grow as cfn-lint supports more regions:

```
cfn-lint --regions us-east-1 us-east-2 us-west-1 us-west-2 ca-central-1 eu-central-1 eu-west-1 eu-west-2 ap-northeast-1 ap-northeast-2 ap-southeast-1 ap-southeast-2 ap-south-1 sa-east-1 eu-west-3 ap-northeast-3 us-gov-west-1 us-gov-east-1 eu-north-1 ap-east-1
```

This could be incredibly helpful for those striving to deploy in every region, like AWS service teams

**Comment by kddejong** [comment]
will be in the next release
