### ISSUE TITLE
FindInMap is allowed within Cidr

### ISSUE THREAD

**Issue by CaseyBurnsSv** [aws-cloudformation/cfn-python-lint#1032]
*cfn-lint version: cfn-lint 0.21.5*

*Description of issue.*

FindInMap is allowed within Cidr - the following code runs successfully in the CFN console, but it reports as an error in cfn-lint.

`!Select [ 2, !Cidr [ !Ref VpcCidrBlock, 4, !FindInMap [CidrBitsMap, !Ref Size, AZCidrBits] ]]`

Gives cfn-lint failure: `E1024:Cidr sizeMask should be Int, Ref, or Select`

See: https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/rules/functions/Cidr.py#L135

**Comment by kddejong** [comment]
Yea I think that logic was originally built off the documentation.   Should be any fix and thanks for reporting this.
 https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-cidr.html#intrinsic-function-reference-cidr-functions

**Comment by kddejong** [comment]
Will be in the next release.
