### ISSUE TITLE
Don't fail rules when running into a Fn::Transform

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-python-lint#1040]
*cfn-lint version: (`cfn-lint --version`)*
v0.22.3
*Description of issue.*
Certain rules are failing when running into a Fn::Transform
![image](https://user-images.githubusercontent.com/36457093/61500908-b0eaad80-a992-11e9-9b9d-7577e507af81.png)

**Comment by kddejong** [comment]
@iDVB going to create a separate issue for this.

**Comment by iDVB** [comment]
Thanks @kddejong,
Can you give a bit more detail as what you mean by 
> “Ideally we would be linting the resulting template from Transforms”

This really is more ideal than actuality, no? Transforms happen on AWS in CFN no? Just curious if I’m missing a step where linting could happen after transform.

**Comment by kddejong** [comment]
@iDVB So for linting the difficult part is that transform can change an "invalid" template to "valid" template.  You are correct it happens on the AWS side.

Example: Resources in this case is a list which isn't standard but the transform makes it valid. https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/ShortHand/example.template

You are using a Transform at a level that we shouldn't have errors but having a larger solution to Transforms is going to take some work.  Ideally at the end of any and all transforms the resulting template is valid CloudFormation template.

**Comment by iDVB** [comment]
Ya, not sure how to lint template-lvl transforms, but snippet lvl ones
should be easier to lint, no?
