### ISSUE TITLE
ElasticLoadBalancingV2 HealthCheckTimeoutSeconds

### ISSUE THREAD

**Issue by n1t1nv3rma** [aws-cloudformation/cfn-python-lint#1075]
*cfn-lint version:* cfn-lint 0.22.3

*Description of issue.*

Complains about E3034 Value has to be between 2 and 60 at Resources/ALBTargetGroup/Properties/HealthCheckTimeoutSeconds 

Whereas it can be upto 120 now as per: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html

**Comment by kddejong** [comment]
Released with v0.23.0
