### ISSUE TITLE
Template files are not being found  in this new release

### ISSUE THREAD

**Issue by JerryValentine** [aws-cloudformation/cfn-python-lint#1079]
*cfn-lint version: 0.23.0

I've been using this linter for about a month now and ever since the update this morning on 8/2/2019 the linter is no longer finding my templates. If I go back to the previous version it does start to work again which makes me think that it has to do with the new update. Additionally, I'm using this in the Azure Devops pipelines.

Code:  - script: cfn-lint -i {W,E0002} -r ${{ variables.awsRegion }} -t $(Build.SourcesDirectory)/*.y*ml --ignore-templates $(Build.SourcesDirectory)/azure-pipelines.yml

**Comment by kddejong** [comment]
looking into this and trying to replicate.  Is there some additional translations here that are occurring before something is passed to cfn-lint? 
Do you know if the translation is causing a pipe to cfn-lint?

`cfn-lint -t test/fixtures/templates/good/*.yaml` still works for me.
`cfn-lint -t test/fixtures/templates/good/.yaml` doesn't work in this version or last so trying to understand how the variable affects the `-t` parameter.

**Comment by kddejong** [comment]
I think #1081 will fix this issue but I'm missing a few details to know for sure.  Since this pull request resolves another issue we are going to push a release and see if your experience is better.

**Comment by chuckmeyer** [comment]
Hi, @JerryValentine -- 0.23.1 is released and includes this small patch. Can you see if it resolves your issue?

**Comment by JerryValentine** [comment]
Yes I just checked and it is working again now thank you!

**Comment by kddejong** [comment]
Sorry for this issue and thanks for your patience.  I believe we have the appropriate tests in place to prevent this from happening going forward.
