### ISSUE TITLE
Missing Specs: me-south-1

### ISSUE THREAD

**Issue by andrew-glenn** [aws-cloudformation/cfn-python-lint#1091]
https://github.com/aws-cloudformation/cfn-python-lint/blob/82bfb546d048c6fd2863ea74af928ddf7f5abd7a/src/cfnlint/maintenance.py#L30-L53

Cross-post to aws-cloudformation-user-guide.   https://github.com/awsdocs/aws-cloudformation-user-guide/issues/421

I assume y'all will just use this for tracking?

**Comment by chuckmeyer** [comment]
Hey @andrew-glenn -- my understanding is this spec hasn't been published yet. We've toyed with the idea of attempting to fabricate a spec file from scratch, but that seemed like overkill. We were hoping to just hang tight until the official spec is published, but would value your opinion on the pros/cons of generating it based on what we can learn from other services (EC2 pricing/SSM)

**Comment by andrew-glenn** [comment]
@chuckmeyer - Happy to wait until the spec is published. I wanted to add the issue for others who came across this and for our own tracking over in TaskCat land.

**Comment by kddejong** [comment]
Merged and waiting on next release.
