### ISSUE TITLE
[new rule] Approaching default limit rules

### ISSUE THREAD

**Issue by PatMyron** [aws-cloudformation/cfn-python-lint#1092]
Definitely not `Error` level, but it could be nice to have some way to know if a template is close to exceeding limits

https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md

**Comment by kddejong** [comment]
We could do an `Info` level error.  Ideas could be.
- Info level error when we hit soft limits?
- Info level error when we hit x% of the hard limit?

What are you thinking for this?

**Comment by chuckmeyer** [comment]
My concern is "hitting limits" is very deployment time -- is it going to be more trouble than it's worth to check this in the linter.  This feels like more of a sister tool that validates against limtis just prior to the create/update call.

(Why do I feel like we've had this conversation before? :)

**Comment by PatMyron** [comment]
@kddejong I was thinking about something like `X%` of the existing rules tagged `limits`

I wasn't thinking about whether the limits were adjustable or not, but that's an interesting separate discussion as well.

The existing experience of being able to choose to ignore a rule and even add a custom rule if your account has adjusted any of its quotas from the default values isn't terrible in my opinion.
