### ISSUE TITLE
How to add custom support for custom resource types

### ISSUE THREAD

**Issue by iDVB** [aws-cloudformation/cfn-python-lint#1115]
![image](https://user-images.githubusercontent.com/189506/64081174-6b2c3f00-cccb-11e9-925b-44e8bad583b2.png)

AWS::S3::Object just get re-written to another supported type by our Macro.

Is there a way to teach the linter to view these custom fields as valid?

**Comment by PatMyron** [comment]
See https://github.com/aws-cloudformation/cfn-python-lint/issues/1382#issuecomment-590119411
