### ISSUE TITLE
Valid EcsParameters (Group, LaunchType, NetworkConfiguration, PlatformVersion) not supported

### ISSUE THREAD

**Issue by headljdghub** [aws-cloudformation/cfn-python-lint#1121]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.23.5

*Description of issue.*
AWS Docs list additional parameters for EcsParameters as part of AWS::Events::Rule that are not supported by cfn-lint.  These docs (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html) list Group, LaunchType, NetworkConfiguration, PlatformVersion as valid parameters but 0.23.5 only supports TaskCount and TaskDefinition.

I don't know if this is related but this page also lists just TaskCount and TaskDefinition: https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-events-rule-ecsparameters.md

Please provide as much information as possible:

-- Example that causes the problem:
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Basic Docker ECS deployment example using code-spawn/warp",
    "Parameters": {
        "Name": {
            "Description": "Name of the api. Will also serve as a sub domain for the custom domain name",
            "Type": "String",
            "Default": ""
        },
        "Environment": {
            "Type": "String",
            "Default": "dev",
            "Description": "Environment name",
            "AllowedValues": [
                "dev",
                "test",
                "prod"
            ],
            "ConstraintDescription": "Must be one of dev, test, or prod"
        },
        "Version": {
            "Description": "Version",
            "Type": "String",
            "Default": "0.0.1"
        },
		"FargateClusterArn": {
			"Type": "String",
			"Default": "",
			"Description": "Arn for the Fargate Cluster"
		},
		"FargateSecurityGroup": {
			"Type": "String",
			"Default": "",
			"Description": "Security Group for the Fargate container"
		},
		"FargateSubnets": {
			"Type": "String",
			"Default": "",
			"Description": "Subnet for the Fargate container"
		},
		"ContainerCpu": {
			"Type": "Number",
			"Default": 1024,
			"Description": "How much CPU to give the container. 1024 is 1 CPU"
		},
		"ContainerMemory": {
			"Type": "Number",
			"Default": 512,
			"Description": "How much memory in megabytes to give the container"
        }
    },
    "Resources": {
            "FargateSchedulingRule": {
                "Type": "AWS::Events::Rule",
                "Properties": {
                    "Name": {"Fn::Sub": "${Environment}-${Name}"},
                    "Description": "Gather EC2 reference data for billing",
                    "ScheduleExpression": "cron(30 18 * * ? *)",
                    "State": "ENABLED",
                    "Targets": [
                        {
                            "Arn": {"Ref": "FargateClusterArn"},
                            "EcsParameters": {
                                "TaskCount": 1,
                                "TaskDefinitionArn": {
                                    "Ref": "TaskDefinition"
                                },
                                "LaunchType": "FARGATE",
                                "PlatformVersion": "LATEST",
                                "NetworkConfiguration": {
                                   "AwsVpcConfiguration": {
                                      "AssignPublicIp": "DISABLED",
                                      "SecurityGroups": [
                                        {"Ref": "FargateSecurityGroup"}
                                      ],
                                      "Subnets": [
                                        { "Fn::Split": [",", {"Ref": "FargateSubnets"}]}
                                      ]
                                   }
                                }
                            },
                            "Id": {"Fn::Sub": "${Environment}-${Name}"},
                            "RoleArn": {
                                "Fn::GetAtt": [
                                    "Role",
                                    "Arn"
                                ]
                            }
                        }
                    ]
                }
            }
    }
}

-- Official documentation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-events-rule-ecsparameters.md

 * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files

I updated cfn-lint and did the 'cfn-lint -u'.  Here is an excerpt from the S3 based file:

https://s3.us-east-1.amazonaws.com/cfn-resource-specifications-us-east-1-prod/latest/CloudFormationResourceSpecification.json

    "AWS::Events::Rule.EcsParameters": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html",
      "Properties": {
        "TaskCount": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html#cfn-events-rule-ecsparameters-taskcount",
          "PrimitiveType": "Integer",
          "Required": false,
          "UpdateType": "Mutable"
        },
        "TaskDefinitionArn": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html#cfn-events-rule-ecsparameters-taskdefinitionarn",
          "PrimitiveType": "String",
          "Required": true,
          "UpdateType": "Mutable"
        }
      }
    },

Then look at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html and you see this:

{
  "Group" : String,
  "LaunchType" : String,
  "NetworkConfiguration" : NetworkConfiguration,
  "PlatformVersion" : String,
  "TaskCount" : Integer,
  "TaskDefinitionArn" : String
}

**Comment by kddejong** [comment]
Looks like the new CloudFormation spec (version 6.0.0) dropped today and included these new properties.  

Release v0.24.1 has these values and is released.
