### ISSUE TITLE
State Machine types missing Map type

### ISSUE THREAD

**Issue by farski** [aws-cloudformation/cfn-python-lint#1137]
The [current list](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/rules/resources/stepfunctions/StateMachine.py#L53) of valid types for state machine tasks is missing the recently-announced [`Map`](https://aws.amazon.com/blogs/aws/new-step-functions-support-for-dynamic-parallelism/) type

**Comment by atkinsonm** [comment]
@kddejong I'm still having this issue on the latest version with updated specs. Any advice?

![image](https://user-images.githubusercontent.com/3342243/66594147-86118f00-eb66-11e9-8882-5f91784aa4b8.png)

![image](https://user-images.githubusercontent.com/3342243/66594129-77c37300-eb66-11e9-8e75-a7c95e69dee4.png)

**Comment by TomasChmelik** [comment]
Parameters aren't allowed for this new Map type. https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-map-state.html?shortFooter=true#map-state-example-params

**Comment by atkinsonm** [comment]
@tomaschmelik great find! I've opened a new issue #1161
