### ISSUE TITLE
Error E3030 Invalid comparison operator 'GreaterThanUpperThreshold' 

### ISSUE THREAD

**Issue by lfacchinelli** [aws-cloudformation/cfn-python-lint#1153]
*cfn-lint version:  0.24.2

*Description of issue.*

While generating a Cloudwatch anomaly alarm and setting the comparison operator to `GreaterThanUpperThreshold` error appears stating that that operator is not valid but, actually, it is.

`Valid values are ['GreaterThanOrEqualToThreshold', 'GreaterThanThreshold', 'LessThanOrEqualToThreshold', 'LessThanThreshold']
`

Not sure if there is an outdated Resource Specification in cfn-lint 0.24.2

**Comment by kddejong** [comment]
Thanks working on a fix for this.

**Comment by kddejong** [comment]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricAlarm.html

Going to update to what is documented here.
