### ISSUE TITLE
cfn-lint fails with `ContextualVersionConflict` on Ubuntu

### ISSUE THREAD

**Issue by DomParfitt** [aws-cloudformation/cfn-python-lint#1158]
*cfn-lint version: (`cfn-lint --version`)* v0.24.4

*Description of issue.* `cfn-lint` fails with `ContextualVersionConflict` on Ubuntu

When trying to run any command using `cfn-lint` on Ubuntu it fails with the following error:

`ContextualVersionConflict: (jsonschema 2.6.0 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('jsonschema~=3.0'), set(['aws-sam-translator']))`

**Comment by kddejong** [comment]
@DomParfitt sorry about that.  We are doing a few things that require a newer version of pip to be available.
