### ISSUE TITLE
CustomResource shows erroneous error when run as library

### ISSUE THREAD

**Issue by danieljamesscott** [aws-cloudformation/cfn-python-lint#1168]
*cfn-lint version: 0.24.5

*Description of issue.*
Error is shown with custom resources when run as a library (not via `cfn-lint` command line).

Please provide as much information as possible:

    {
      "AWSTemplateFormatVersion": "2010-09-09",
      "Description": "Description",
      "Resources": {
        "Custom": {
          "Type": "Custom::Resource",
          "Version": 1.0,
          "Properties": {
            "ServiceToken": {
              "Fn::Sub": "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:topic"
            },
            "Type": "Custom"
          }
        }
      }
    }

Code:

        rules = cfnlint.core.get_rules([], ["W", "E301", "E3001", "E303", "E3008", "E3005", "E3006", "E3004", "E3003",
                                            "E305", "E35", "E1", "E2", "E8", "E4", "E7",
                                            "E302", "E6"], [])

        # Use us-east-1 region (spec file) for validation
        regions = ["eu-west-1"]

        with open("minimal.json", 'r') as f:
            template = json.load(f)

            # Process all the rules and gather the errors
            matches = cfnlint.core.run_checks(
                "cf.json",
                template,
                rules,
                regions)

            for match in matches:
                print(match)

When run, this code outputs:

    [E0002: Error processing rule on the template] (Unknown exception while processing rule E3002: 'dict' object has no attribute 'is_function_returning_object')

Which appears to be caused by this line:

https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/rules/resources/properties/Properties.py#L240

The `text` field is a simple `dict` containing my custom resource, so the method `is_function_returning_object()` does not exist.

**Comment by kddejong** [comment]
I'll take a look.  Thanks for reporting this.

**Comment by kddejong** [comment]
@danieljamesscott in this doc we ask that you use our decoder.  I don’t see that line above. Is it just missing? Or did you do your own decode? https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/getting_started/integration.md#getting-started

**Comment by danieljamesscott** [comment]
Thanks for the reply, that's correct - I wasn't using the correct decoder.

    cfnlint.decode.cfn_json.load()

works fine
