### ISSUE TITLE
Parameter to pick the location of .cfnlintrc

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-python-lint#1170]
Requesting to add a parameter that allows a user to specify a path to a `.cfnlintrc` file.  Right now those are only a few locations we look for a `.cfnlintrc` file.  We would like to allow a user to specify that location.

**Comment by Jhonatangiraldo** [comment]
Hello! What's the status of this task? Is someone working on this?

**Comment by kddejong** [comment]
Sorry @Jhonatangiraldo.  I missed this.  I was going to pick this up this week unless you would like to take it.

**Comment by kddejong** [comment]
So digging this into today.  The question I have is if a path is specified do we not look into any other .cfnlintrc files?  Right now we look at a users config file a "projects" config file and we merge them together.  

we have 2 options here.
1.  Merge the custom config file with the other 2
2. Not load the other 2 at all and only use the one specified.  

thoughts?

**Comment by PatMyron** [comment]
> 2. Not load the other 2 at all and only use the one specified.
