### ISSUE TITLE
--append-rules from S3 bucket

### ISSUE THREAD

**Issue by mrpackethead** [aws-cloudformation/cfn-python-lint#1192]
This is a feature request, 

It would be really nice if we could specify an S3 bucket for  --append-rules.  This would make it easy to share custom rules across our organisation / codebuilder

**Comment by mrpackethead** [comment]
This is What I ended up doign with my Buildspec.   AS you can see its copying some files across from S3.   I have another pipleine that migrates the contents of a Repo to the S3 bucket, when they are committed.    The S3 bucket is available for our team to read, so they can use our custom rules.
I imagine something like this;

cfn-lint template.yaml --append-rules-from-s3 s3://s3bucketname --profile my-aws-profile

I will have a look at the source, this might not be so hard to implement myself.






`BuildSpec: |
            version: 0.2
            phases:
              install:
                commands: 
                  - pip install cfn-lint
                  - mkdir msrules
                  - cd msrules
                  - aws s3 cp s3://cfn-lint-rules . --recursive
                  - cd ..
              build:
                commands:
                  - cfn-lint template.yaml --append-rules msrules
            artifacts:
              type: zip
              discard-paths: yes
              files: template.yaml`

**Comment by PatMyron** [comment]
Going to lean on the side of [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) where other tools solve fetching remote files better, especially if handling credentials, and I'd recommend the solution you landed on

similar issues: https://github.com/aws-cloudformation/cloudformation-guard/issues/24, https://github.com/aws-cloudformation/cfn-python-lint/issues/1094
