### ISSUE TITLE
typo in docb DocumentDBEngineVersion AllowedValues

### ISSUE THREAD

**Issue by oazmon** [aws-cloudformation/cfn-python-lint#1202]
*cfn-lint version: (`cfn-lint --version`)*

*Description of issue.*
The CloudSpecs/*.json files specify a DocumentDBEngineVersion AllowedValues of 'docdb'
At least in us-west-2 this is incorrect and the actual underlying system requires "docdb 3.6.0" or the CFN fails create and rolls back. Would have produced a PR but not sure if same in all regions.

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by kddejong** [comment]
incorrect in us-east-1 as well.  Going to update this for all cases.  Thanks for sending this in.

**Comment by kddejong** [comment]
I can only get '3.6.0' to work.  You sure you had "docdb 3.6.0"
