### ISSUE TITLE
Support python3.8 for Lambda runtime

### ISSUE THREAD

**Issue by atkinsonm** [aws-cloudformation/cfn-python-lint#1205]
*cfn-lint version: (`cfn-lint --version`)* 0.24.6

*Description of issue.*

Python3.8 is not yet recognized as a valid value for Lambda function runtime. The latest version recognized by the spec is python3.7. Specifying python3.8 returns `E3030: Check if properties have a valid value`

**Comment by kddejong** [comment]
Fixed with #1204

**Comment by kddejong** [comment]
Released with https://pypi.org/project/cfn-lint/0.25.2/

**Comment by atkinsonm** [comment]
Thanks @kddejong!
