### ISSUE TITLE
Support appending rules from installed packages

### ISSUE THREAD

**Issue by zroger** [aws-cloudformation/cfn-python-lint#1209]
I would like to create a python package of my organization's custom rules, which could be installed alongside `cfn-lint` and then referenced from the CLI and/or `.cfnlintrc` by import path rather than directory path.

For example, with a custom package named `myrules` and a module within that package named `recommended`:

```shell
# install via pip
pip install cfn-lint
pip install myrules

# invoke via CLI
cfn-lint -a myrules.recommended ...
```

```yaml
# or in .cfnlintrc
append_rules:
  - myrules.recommended
```

I'm happy to put together a PR if this is something that would be considered.

**Comment by kddejong** [comment]
I like this idea.  I wonder how hard it would be to accomplish.  I'm open to it.

**Comment by kddejong** [comment]
I  believe this is complete.  Closing.  We can reopen if needed.
