### ISSUE TITLE
Help adding custom/experimental rule

### ISSUE THREAD

**Issue by tazatwell** [aws-cloudformation/cfn-python-lint#1210]
*cfn-lint version: `0.25.2`*

Hi, I am trying to create a custom cfn-lint rule for my organization, which ensures that parameters called for nested stacks are correct.

I have already written the logic for this, but I'm having trouble including it in cfn-lint as a rule.

I have a directory called `cfn-lint-rules` that includes a file `checkParams.py`. 

That file has a class with the definition: `class checkParams(CloudFormationLintRule):` It has the values: `id = E9001` and `experimental = True`.

The class has a function definition, `def checkParams(self, cfn):`, with my logic in it. It returns a list of `RuleMatch(messages)`.

I tried invoking cfn-lint using: `cfn-lint -a cfn-lint-rules -e TEMPLATE.yaml`, but it does not include my rule. My own script  correctly outputs that the template is improperly calling a nested template w/ incorrect parameters, but cfn-lint does not, which makes me think that it is not being called correctly.

Any info on this, or even links to documentation on how to include a rule, would be greatly  appreciated. I can provide more info on request.

Thanks, and have a nice day :)

**Comment by kddejong** [comment]
Looks like you have it correct.  I will try replicate to see if there are any differences.

**Comment by tazatwell** [comment]
Hi, I copied the format specified in `cfn-python-lint/examples/rules/`, since those files were working.

I copy/pasted my logic in that file since its rule was included, then renamed the file and class name. Not sure what the original error was, but for anyone seeking to add a  custom rule, this is a good way to add it.

I'll close the issue. 


Thank you for the help, have a nice day :)
