### ISSUE TITLE
Support for AWS::RDS::DBCluster property EnableHttpEndpoint

### ISSUE THREAD

**Issue by iamed2** [aws-cloudformation/cfn-python-lint#1217]
*cfn-lint version: 0.25.2*

EnableHttpEndpoint is a [documented](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enablehttpendpoint) property for AWS::RDS::DBCluster (and it is possible to deploy a stack using this property) but is not present in the latest CloudFormation specs. Is it possible for `cfn-lint` to allow this property? If you must stick to the specs, do you know the best place to report such an issue to AWS?

**Comment by kddejong** [comment]
We do have a patching process so we should be able to patch that in.

**Comment by PatMyron** [comment]
[Released this week](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)

See https://github.com/aws-cloudformation/cfn-python-lint/issues/1219#issuecomment-557935139
