### ISSUE TITLE
How does linter get line, character number info?

### ISSUE THREAD

**Issue by tazatwell** [aws-cloudformation/cfn-python-lint#1218]
*cfn-lint version: cfn-lint 0.25.2*

Hi,

Quick question, but is there a way to get the line and character info of a yaml file how the linter does? 

I noticed that the built-in exceptions are able to retrieve that info nicely, and I'm trying to see if I can avoid writing a parser for it.

As for as I know, say I have an experimental rule defined by: `class check_param_references(CloudFormationLintRule):` with a function `def match(self, cfn):`. As far I can tell, the `cfn` object only has a filename. How does the linter retrieve the line and character info for where the error is located?

Thanks :) have a nice day

**Comment by kddejong** [comment]
We use custom decoding of a YAML/JSON file.  
https://github.com/aws-cloudformation/cfn-python-lint/tree/master/src/cfnlint/decode

When we parse out the yaml file we use Classes that extend strings, dicts, lists, etc.  Example: https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/decode/node.py#L29-L30

**Comment by kddejong** [comment]
Additionally when creating a Match if you put the path to the error.  [Resources, ResourceName, Properties, Property, etc.] the core functionality will traverse down the yaml and get the location information.

**Comment by tazatwell** [comment]
Hi, I'm trying to create a `RuleMatch` object with: `newRule = RuleMatch(path=["Resources"], message="")`


Then I'm trying to append a Match object to my rules with: `matches.append(Match(linenumber=1, columnnumber=2, linenumberend=3, columnnumbered=4, filename="", rule=newRule))`


When I run with my custom rule I get: `E0002 Unknown exception while processing rule E9001: can only concatenate str (not "type") to str`


I believe only the `RuleMatch` class takes a `path` as a parameter to its constructor. How do I pass in the path to get the line and character info?

I can provide more info on request. Thank you! :)

**Comment by kddejong** [comment]
The rule should just return the RuleMatch.  The core libraries will convert it to a Match.

Very simple rule so it may be the best way to describe it.
https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/rules/templates/LimitDescription.py#L27

**Comment by kddejong** [comment]
Here is where we translate it to a Match.

https://github.com/aws-cloudformation/cfn-python-lint/blob/f0db732265b6f2b05e01bb083e5c3785703edfda/src/cfnlint/rules/__init__.py#L94-L106

**Comment by tazatwell** [comment]
thanks so much for the example, I'll close the issue :)
