### ISSUE TITLE
`EnableVersionUpgrade` Update Policy Not Recognized

### ISSUE THREAD

**Issue by chrisoverzero** [aws-cloudformation/cfn-python-lint#1230]
*cfn-lint version: (`cfn-lint --version`)* 0.25.5

*Description of issue:*

cfn-lint does not understand `AWS::Elasticsearch::Domain`'s new `UpdatePolicy` of `EnableVersionUpgrade`. This key accepts a Boolean value.

> If `EnableVersionUpgrade` is set to true, you can update the `ElasticsearchVersion` property of the `AWS::Elasticsearch::Domain` resource, and CloudFormation will update that property without interruption. When `EnableVersionUpgrade` is set to `false`, or not specified, updating the `ElasticsearchVersion` property results in CloudFormation replacing the entire `AWS::Elasticsearch::Domain` resource.

I have a patch for this ready to go, and the PR should be created in a couple of minutes.

**Comment by kddejong** [comment]
Thanks @chrisoverzero
