### ISSUE TITLE
Invalid or unsupported Type AWS::EKS::Nodegroup

### ISSUE THREAD

**Issue by jldsLopez** [aws-cloudformation/cfn-python-lint#1250]
*cfn-lint version: (`vscode-cfn-lint --v0.10.2`)*

*Description of issue.*

* Template linting issues:
  * Newly AWS EKS have included a new resource type called: **AWS::EKS::Nodegroup** but current vscode-cfn-lint version (v0.10.2) don't support it and say: _Invalid or unsupported Type AWS::EKS::Nodegroup for resource_
* Feature request:
  * Please provide support to **AWS::EKS::Nodegroup** resource type

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by kddejong** [comment]
The VS Code plugin relies on `cfn-lint` to do its work.  `cfn-lint` needs to have the spec files updated.  That can be done doing `cfn-lint --update-specs` or by updating the version.  Version v0.25.5 includes the property `AWS::EKS::Nodegroup` so an update should get you fixed.
