### ISSUE TITLE
Support FirelensConfiguration.

### ISSUE THREAD

**Issue by alexey-ktx** [aws-cloudformation/cfn-python-lint#1254]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.25.0

*Description of issue.*
This version of cfn-lint still detects [FirelensConfiguration](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_FirelensConfiguration.html)  as an error. I know this is a pretty new feature in ECS/Fargate but my organization is planning to use it and we need to pass the cfn-lint tests in our pipelines before deploying our infrastructure. Now it is not possible and is a big concern to us.

**Comment by kddejong** [comment]
It should be there as of v0.25.5. What version are you using?  The other methodology to update is to do “cfn-lint —update-specs”.  Either an upgrade or the update specs should fix your issue.

**Comment by PatMyron** [comment]
Yup, should be in the [latest `us-east-1` CloudFormation Resource Specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json). Updating should fix this
