### ISSUE TITLE
Add get_output function to Template class

### ISSUE THREAD

**Issue by danieljamesscott** [aws-cloudformation/cfn-python-lint#1264]
*cfn-lint version: 0.26.0*

Is it OK to add a `get_output` function to the `Template` class?

I'm trying to add a lint rule which ensures that all of our stacks contain a specific output and I can't find a way of doing this. I was thinking it would be good to have a method such as:

     def get_output(name) -> Output:

and/or

    def get_outputs() -> List[Output]

I can do a PR for this if you think it's a good idea?

(Out of interest, is anyone interested in adding type hints to the code base? I find them very useful)

**Comment by kddejong** [comment]
I think that is a good option to have.

Typically when we make those things we do a basic syntax check so that each rule doesn't have to also have that logic.

**Comment by danieljamesscott** [comment]
So I can add the functionality to get the outputs from the template, and a rule which does a basic syntax check?

**Comment by PatMyron** [comment]
[Top-level template sections](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html) can generally use:
`cfn.template.get('Outputs', {})`
which is what most of the [`outputs` rules](https://github.com/aws-cloudformation/cfn-python-lint/tree/master/src/cfnlint/rules/outputs) do

---

The [`Resources`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html) section is the only section which also has a `cfn.get_resources()` function that wraps `cfn.template.get('Resources', {})` to provide additional validation similarly discussed in https://github.com/aws-cloudformation/cfn-python-lint/issues/1521

https://github.com/aws-cloudformation/cfn-python-lint/blob/52c02962e90354b265fec839e71e1d038e899fd4/src/cfnlint/template.py#L63-L99
