### ISSUE TITLE
Add support for nodejs12.x

### ISSUE THREAD

**Issue by kamlakant** [aws-cloudformation/cfn-python-lint#1274]
`cfn-lint version: (cfn-lint 0.26.1)`

*Description of issue*

* Feature request 

AWS Lambda now supports Node.js 12. However, cfn-lint doesn't support it yet.
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/

Running cfn-lint against template with nodejs12.x lambda results in below error
`E3030 You must specify a valid value for Runtime (nodejs12.x).
Valid values are ['dotnetcore1.0', 'dotnetcore2.0', 'dotnetcore2.1', 'go1.x', 'java8', 'nodejs', 'nodejs4.3-edge', 'nodejs4.3', 'nodejs6.10', 'nodejs8.10', 'nodejs10.x', 'provided', 'python2.7', 'python3.6', 'python3.7', 'ruby2.5']`

**Comment by kddejong** [comment]
Are you sure you are using version 0.26.1?  Node.js was put in with PR #1204 and included in release [0.25.2](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CHANGELOG.md#0252)

**Comment by kamlakant** [comment]
Ah! Messed up pip and homebrew installations. Thanks for the quick reply. Closing the issue.
