### ISSUE TITLE
S3 WebsiteConfiguration validations incorrect

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/cfn-python-lint#1282]
*cfn-lint version: cfn-lint 0.26.2*

*Description of issue.*

In an AWS::S3::Bucket, the WebsiteConfiguration.RoutingRules[0].RoutingRuleCondition can have both the `HttpErrorCodeReturnedEquals` and `KeyPrefixEquals` keys specified (linter says you can only have one).

https://github.com/aws-cloudformation/cfn-python-lint/blob/58568ca1cbab3a6cb810564e3af72162cb13b48f/src/cfnlint/data/AdditionalSpecs/OnlyOne.json#L63-L68

Additionally you should only have one of the WebsiteConfiguration.RoutingRules[0].RedirectRule properties `ReplaceKeyPrefixWith` and `ReplaceKeyWith` (there is no rule for this currently).

**Comment by kddejong** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-websiteconfiguration-routingrules-routingrulecondition.html

Looking at this. If I'm deciphering this correctly at least one is required when using a condition.

**Comment by iann0036** [comment]
I never actually tested whether it was OnlyOne or AtLeastOne :)
