### ISSUE TITLE
"E0000 found unknown escape character 'd'" received on Allowed Pattern from Cloud9 doc

### ISSUE THREAD

**Issue by FireballDWF** [aws-cloudformation/cfn-python-lint#1299]
*cfn-lint version: (`cfn-lint --version`)* cfn-lint 0.26.2

*Description of issue.*
"E0000 found unknown escape character 'd'" received on Allowed Pattern from Cloud9 doc

    AllowedPattern: "^arn:aws:(iam|sts)::\d+:(root|(user\/[\w+=/:,.@-]{1,64}|federated-user\/[\w+=/:,.@-]{2,32}|assumed-role\/[\w+=/:,.@-]{1,64}\/[\w+=/:,.@-]{1,64}))$"

which is the same as the Allowed Pattern documented for OwnerArn at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud9-environmentec2.html#aws-resource-cloud9-environmentec2-properties

**Comment by kddejong** [comment]
@FireballDWF it has to do with the double quotes.

With double quotes the `\` becomes an escape character.
`AllowedPattern: "^arn:aws:(iam|sts)::\d+:(root|(user\/[\w+=/:,.@-]{1,64}|federated-user\/[\w+=/:,.@-]{2,32}|assumed-role\/[\w+=/:,.@-]{1,64}\/[\w+=/:,.@-]{1,64}))$"` 

If you do this it will be valid.
`AllowedPattern: ^arn:aws:(iam|sts)::\d+:(root|(user\/[\w+=/:,.@-]{1,64}|federated-user\/[\w+=/:,.@-]{2,32}|assumed-role\/[\w+=/:,.@-]{1,64}\/[\w+=/:,.@-]{1,64}))$`

**Comment by FireballDWF** [comment]
Ah, thanks for explaining that
