### ISSUE TITLE
Linting exception for valid SAM Api resource

### ISSUE THREAD

**Issue by JustinLiang90** [aws-cloudformation/cfn-python-lint#1325]
#### Description of issue

`RestApiId` is not recognised as a valid type for type `AWS::Serverless::Function`

```
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: The cloudformation includes all lambda definitions.

Globals:
  Function:
    Runtime: go1.x
    Timeout: 5
    Handler: main

Parameters:
  AllowedCORSDomain:
    Type: String
  ParentStackName:
    Type: String
  ApiGatewayStageName:
    Type: String
  StripePrivateKey:
    Type: String

Resources:
  HelloWorldFunction:
    Properties:
      CodeUri: ../go/lambda/hello-world/
      Events:
        Api:
          Properties:
            Method: Get
            Path: /
            RestApiId:
              Ref: ApiGateway
          Type: Api
      FunctionName: Hello-world
    Type: AWS::Serverless::Function

  ApiGateway:
    Properties:
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: !Ref AllowedCORSDomain
      DefinitionBody:
        openapi: '3.0'
        bathPath: /
        schemes:
          - https
        paths:
          /hello:
            get:
              responses:
                '200': {}
              x-amazon-apigateway-integration:
                type: 'aws_proxy'
                httpMethod: 'POST'
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: /*
      Name: Hello-world-ApiGateway
      OpenApiVersion: '2.0'
      StageName: dev
    Type: AWS::Serverless::Api

```

The way of setting APIGateway comes from [aws document](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-resource-api--examples). 

#### Error:
```
Error transforming template: unhashable type: 'dict_node' [E0001]. 
```
If comment out `RestApiId: !Ref ApiGateway`, then works.

**Comment by kddejong** [comment]
@JustinLiang90 can you do a `pip list` and tell me what version of `aws-sam-translator` you have?

`E0001` on a SAM translator are the result of us getting an error back from that package.  I haven't been able to replicate the issue so I'm wondering if you have a different version of that package than I do.

**Comment by JustinLiang90** [comment]
> can you do a `pip list` and tell me what version of `aws-sam-translator` you have?

@kddejong `aws-sam-translator` version is `1.20.1`

**Comment by mkamioner** [comment]
Having the same problem!

cfn-lint = 0.27.1
aws-sam-translator = 1.20.1

**Comment by kddejong** [comment]
thanks was able to replicate.  Weirdly enough not an issue in 1.19.1.  Going to have to dig into their code to see what may have changed.  Sometimes we have to do a little prep to a template before we send it to them and that may have changed with this newer release.

**Comment by kddejong** [comment]
For my reference
```
Traceback (most recent call last):
  File "cfn-python-lint/src/cfnlint/transform.py", line 113, in transform_template
    parameter_values=self._parameters))
  File "samtranslator/translator/translator.py", line 120, in translate
    resource_dict, intrinsics_resolver
  File "samtranslator/translator/translator.py", line 65, in _get_function_names
    self.function_names[api_name] = str(self.function_names.get(api_name, "")) + str(
```

**Comment by kddejong** [comment]
https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/translator/translator.py#L55

Would be better stated as 
`if isinstance(rest_api, (dict, OrderedDict)):`

**Comment by kddejong** [comment]
https://github.com/awslabs/serverless-application-model/issues/1410

**Comment by kddejong** [comment]
https://github.com/awslabs/serverless-application-model/pull/1411

**Comment by igordssousa** [comment]
This also happens to me when using:
`FunctionName: !Sub "${FunctionNamePrefix}-order"`

We had to stop using cnf-lint because of this.

Will the fix also correct this? Any estimate on when it will be released?

**Comment by kddejong** [comment]
@igordssousa I'll have to test it out.  Thanks for sharing the issue you ran into... I'll see how we can get it resolved.

**Comment by keetonian** [comment]
Hopefully fixing this in the v1.21.0 release of SAM, which should be out soon.

**Comment by kddejong** [comment]
thanks @keetonian  Fixed and released. Closing this issue as an update to sam translator should fix the issue.
