### ISSUE TITLE
Missing support for AWS::ACMPCA

### ISSUE THREAD

**Issue by erik-hillbom-wcar** [aws-cloudformation/cfn-python-lint#1332]
Missing lint support for newly release AWS::ACMPCA

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ACMPCA.html

**Comment by PatMyron** [comment]
[`AWS::ACMPCA`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ACMPCA.html) is in the latest [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html)

`cfn-lint -u` will update the Resource Specifications your linter is using to the latest versions

**Comment by kddejong** [comment]
will be released shortly.  #1333
