### ISSUE TITLE
errors parsing WAFv2 Adresses and Tags

### ISSUE THREAD

**Issue by markvp** [aws-cloudformation/cfn-python-lint#1342]
*cfn-lint version: 0.27.3*

*Description of issue.*

As per #1312, there are similar discrepancies between the documentation (and thus the linter) and the actual required structure when it comes to:
* IPSet.Tags should be an array of objects with key / value properties, not an object as documented: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-ipset.html#cfn-wafv2-ipset-tags
* IPSet.Addresses should be an array of strings, not an object as documented: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-ipset.html#cfn-wafv2-ipset-addresses
* WebACL.Tags should be an array of objects with key / value properties, not an object as documented: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-webacl.html#cfn-wafv2-webacl-tags

Each of these produces the error "E3002: Expecting an object at {above locations}" if using the correct and working syntax (arrays) and fails on deployment if using the successfully parsed but incorrect syntax (objects).

**Comment by kddejong** [comment]
agreed @markvp should be easy to patch this up

**Comment by kddejong** [comment]
@markvp can you look at this https://github.com/aws-cloudformation/cfn-python-lint/pull/1343/files#diff-cba5d17ded675186863e2dc01a557bfbR183-R261. validate that it looks right to you

**Comment by markvp** [comment]
Looks good to me :)
