### ISSUE TITLE
Incorrect resource type for hover and resource documentation link

### ISSUE THREAD

**Issue by sliedig** [aws-cloudformation/cfn-python-lint#1346]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.27.4

*Description of issue.*

In VS Code, if you hover over resources that have the Serverless or Amplify namespace, it gets interpreted as a AmazonMQ resource, and links you to that product documentation e.g.

- AWS::Serverless::Function
- AWS::Serverless::Api
- AWS::Amplify::Branch
- AWS::Amplify::App

![image](https://user-images.githubusercontent.com/597073/74005782-ee596b80-49b4-11ea-9ca8-0263aad51e59.png)

**Comment by kddejong** [comment]
@sliedig I'll take a look into this.  I want to make sure the data itself isn't bad.  

That being said we are using another package that provides the yaml capabilities.  We just provide the file and settings to configure it.   I'm not sure this will be inside our control but I want to make sure we are providing the most accurate data to that language server first.

**Comment by PatMyron** [comment]
@kddejong explained in https://github.com/awslabs/aws-cfn-lint-visual-studio-code/pull/71#issuecomment-572162661

---

https://github.com/awslabs/aws-cfn-lint-visual-studio-code/pull/76 adds [`AWS::Amplify::Branch`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-branch.html), [`AWS::Amplify::App`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html), etc

That commit still needs to be published to the [marketplace](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint)

---

The [Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) and [Template Schema](https://github.com/aws-cloudformation/aws-cloudformation-template-schema) don't include [`AWS::Serverless`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html) resource types, so documentation links and autocomplete still won't work for those

**Comment by PatMyron** [comment]
@sliedig new extension version published to the [marketplace](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint) fixes documentation links and autocomplete for non-[`AWS::Serverless`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-resources-and-properties.html) resource types
