### ISSUE TITLE
Rule IDs

### ISSUE THREAD

**Issue by lingrlongr** [aws-cloudformation/cfn-python-lint#1353]
The documentation for rule IDs shows that they represented by `[EWI]\d{4}`.  Is there anything in the codebase that would prevent a longer rule ID?  For example, `E95001`.

I was successfully able to run it, but wanted to make sure that crafting longer IDs was not a problem for now and for future.

Thanks!

**Comment by kddejong** [comment]
I don't have any plans on requiring that it only be 4 #s.  We use the first letter to determine the error level, the first number to try classify the error, but past that we really don't care.  I think you should be good to go.  We could also add a test for this to make sure we don't add anything in the future that would break this.

**Comment by lingrlongr** [comment]
Wonderful news!!  Thanks!
