### ISSUE TITLE
--format JUnit XML reporting file format

### ISSUE THREAD

**Issue by steven-cuthill-otm** [aws-cloudformation/cfn-python-lint#1368]
**Feature request** 
Would be really handle if we can get some more formatting options for popular test frameworks, for example JUnit XML. 

These frameworks integrate into many build pipeline technologies for an integrated test reporting.

As it stands cfn-python-lint runs as a scripted step and will exit with errors if there are any structural issues with the templates. ideally i would like the output to be formatted into JUnit XML with results of each tested resources. this file is picked up by our build framework and the pipline will pass or fail based on the results of the test run, the same way we do for code tests.

**Comment by bryanburke** [comment]
I second this. Being able to ingest the linting results for display in a tool like Jenkins would be very useful, especially for review my non-developer cloud architects. Ant's JUnit XML schema is here for reference: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd
