### ISSUE TITLE
Custom Types/Resources + Macros/Transforms

### ISSUE THREAD

**Issue by iDVB** [aws-cloudformation/cfn-python-lint#1382]
Is there a way to get `cfn-lint` to be friends with templates that implement custom resources that have a custom Type like `Type: DVB::StackProxy::ProxyEntry`  and that are later transformed with a Macro? 

Seems like it would need a way to add further rules…. would something like this work `--append-rules` ?

**Comment by PatMyron** [comment]
Sorry for missing https://github.com/aws-cloudformation/cfn-python-lint/issues/1115 the first time around. Until more [support for Fn::Transform](https://github.com/aws-cloudformation/cfn-python-lint/issues/476) exists, linting the transformed template, ignoring specific violations, or [supporting resource types schemas](https://github.com/aws-cloudformation/cfn-python-lint/issues/1277) seem like the most viable options

**Comment by iDVB** [comment]
Thanks @PatMyron, in a pinch, could people use that additional rules flag and add support?

**Comment by PatMyron** [comment]
> Thanks @PatMyron, in a pinch, could people use that additional rules flag and add support?

Adding additional rules won't help with the existing rules getting flagged in this situation

Ignoring existing rules while adding additional custom rules to cover the ignored rules is definitely a possibility, but probably more difficult than some of the other options
