### ISSUE TITLE
Check for allowed engine name in AWS::RDS::DBInstance

### ISSUE THREAD

**Issue by atkinsonm** [aws-cloudformation/cfn-python-lint#1396]
*cfn-lint version: (`cfn-lint --version`)* 0.28.2
*Using latest spec*

*Description of issue.*

`cfn-lint` does not currently warn/error when an [`AWS::RDS::DBInstance`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html) is using an illegal value for the `Engine` property.

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/data/ExtendedSpecs/all/03_value_types/aws_rds.json

https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/data/ExtendedSpecs/all/04_property_values/aws_rds.json
