### ISSUE TITLE
[Request] TAP-compliant output

### ISSUE THREAD

**Issue by bryanburke** [aws-cloudformation/cfn-python-lint#1429]
[Test Anything Protocol](http://testanything.org/), TAP for short, is a simple plain text protocol for communication of test results between tools in a language-agnostic way. TAP-formatted results are parseable by a variety of libraries and tools, and several tools exist to convert between TAP and other common formats such as JUnit XML. Support for TAP-compliant output would be useful in automated CI workflows, where a variety of testing and static analysis tools often come together to produce a more complete picture of code quality.

**Comment by PatMyron** [comment]
Interesting, reminds me a bit of https://github.com/grantmcconnaughey/Lintly/pull/8

Documenting an [integration like this](https://github.com/wbazant/shellcheck-tap-integration) here would be my preference

**Comment by kddejong** [comment]
Similar request to #1368 .  
The formatting could get a little weird with what are doing today.  ESlint looks like they do this.  https://eslint.org/docs/user-guide/formatters/#tap  Kind of an interesting format where the first error gets the top level and then additional records are put in `messages`.  This would be possible but I'm not sure I like that formatting.  

We would have to maintain the ability to output multiple file errors.

**Comment by bryanburke** [comment]
I don't like ESLint's TAP output format either. I think having each result in the TAP output be the intersection of a file name, line number, and error/warning would probably be more usable. The [YAML blocks](http://testanything.org/tap-version-13-specification.html#yaml-blocks) in the TAP 13 spec seem to be more appropriate for holding additional diagnostic metadata than lists of errors.

**Comment by PatMyron** [comment]
> several tools exist to convert between TAP and other common formats such as JUnit XML

might be able to convert from [JUnit](https://github.com/aws-cloudformation/cfn-python-lint/pull/1506) or one of the [other formats](https://github.com/aws-cloudformation/cfn-python-lint/#parameters) without official support

We won't be officially picking this up anytime soon, so I'm going to close this out for now, but feel free to update here if anyone else looks into this
