### ISSUE TITLE
Support AWS::ResourceGroups:Group resources

### ISSUE THREAD

**Issue by coyoteecd** [aws-cloudformation/cfn-python-lint#1440]
*cfn-lint version: (`cfn-lint --version`)* 0.29.0

I tried to deploy an AWS resource group and cfn-lint complains that it's not supported.
Documentation can be found here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-resourcegroups-group.html

Looks like another case of specs lagging behind the actual AWS releases (#1219)

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/pull/1433 hasn't been released yet, but [`AWS::ResourceGroups:Group`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-resourcegroups-group.html) is in the latest [CloudFormation Resource Specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json). Running this should fix it:

`cfn-lint --update-specs`

**Comment by kddejong** [comment]
v0.29.1 is being released now or do what @PatMyron suggested.  Should be fixed either way very shortly.
