### ISSUE TITLE
E3001 AWS::Glue::Table and AWS::Glue::Database in us-west-1

### ISSUE THREAD

**Issue by markadrianagbuya** [aws-cloudformation/cfn-python-lint#1452]
*cfn-lint version: 0.29.2*

*Description of issue.*
```
E3001 Invalid or unsupported Type AWS::Glue::Database for resource GlueDatabase in us-west-1
E3001 Invalid or unsupported Type AWS::Glue::Table for resource GlueTable in us-west-1
```

However, AWS says [Glue is available in US West N. California Region](https://aws.amazon.com/about-aws/whats-new/2018/12/aws-glue-is-now-available-in-us-west-north-california-aws-region/). I was able to run create stack successfully with the Glue Database.

*CloudFormation sample that generated the issue*
```
...
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: 'Events database'
        Name: !Sub '${EnvironmentName}_company'
...
```

Running `cfn-lint -u` didn't resolve the issue

**Comment by PatMyron** [comment]
[`AWS::Glue::Table`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-table.html) + [`AWS::Glue::Database`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-database.html) now in the [`us-west-1` Resource Specification](https://d68hl49wbnanq.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json):

```shell
cfn-lint --update-specs
```
