### ISSUE TITLE
[feature request] argument for specifying path to configuration file

### ISSUE THREAD

**Issue by craighurley** [aws-cloudformation/cfn-python-lint#1457]
**Feature request**

*cfn-lint version*: `0.29.4`

There is no argument for specifying the path to a configuration file (`.cfnlint.rc`).  It would be useful to be able to specify a path when running `cfn-lint` from a directory that does not contain `.cfnlint.rc`.  This is particularly useful when you want to run `cfn-lint` from a docker container and when you/your team has many `ignore_checks`, `templates` (paths) and `ignore_templates` (paths).

**Comment by PatMyron** [comment]
Tracking here: https://github.com/aws-cloudformation/cfn-python-lint/issues/1170
