### ISSUE TITLE
Variable interpolation

### ISSUE THREAD

**Issue by lingrlongr** [aws-cloudformation/cfn-python-lint#1460]
*cfn-lint version: (0.29.2)*

*Description of issue.*

Hi.  I'm trying to write a custom rule that will evaluate IAM policies.  I'm at a point where I'm trying to evaluate an IAM policy statement.  Something like:

    {
        "Effect": "Allow",
        "Action": [
            "cloudformation:DescribeStacks"
        ],
        "Resource": [
            {
                "Fn::Sub": "${AWS::StackId}"
            }
        ]
    }

The variables could be either CF template pseudo-variables, like `${AWS::Region}`,  intrinsic functions like `{"Fn::Sub": "..."}` `{ "Fn::GetAtt": "..."}`, `{"Fn::ImportValue": "..."}`, `{"Ref": "..."}`, etc...

Is there anything in the cfn-lint library that will interpolate values like this and provide the result?

**Comment by PatMyron** [comment]
There's really no way for the Linter to evaluate resolved values for some of these without credentials and networking, but there are at least helpers to recognize that they are present:

https://github.com/aws-cloudformation/cfn-python-lint/blob/53a0983bf66970f8888569cdf0fbd1120727c665/src/cfnlint/helpers.py#L121-L130

https://github.com/aws-cloudformation/cfn-python-lint/blob/53a0983bf66970f8888569cdf0fbd1120727c665/src/cfnlint/helpers.py#L74-L76

**Comment by lingrlongr** [comment]
Fair statement.  Thanks!
