### ISSUE TITLE
Support latest dotnet runtime

### ISSUE THREAD

**Issue by dbaghdanov** [aws-cloudformation/cfn-python-lint#1468]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.29.5

*Description of issue.*
cfn-lint reports: 
E3030 You must specify a valid value for Runtime (dotnetcore3.1)

It is supported in the spec however: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime

**Comment by PatMyron** [comment]
@dbaghdanov thanks for the report, [next release](https://github.com/aws-cloudformation/cfn-python-lint/releases) should have this
