### ISSUE TITLE
Add telemetry

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/cfn-python-lint#1512]
*cfn-lint version: (`cfn-lint --version`)* N/A

*Description of issue.* Right now, the only mechanism we have for gathering feedback is GitHub issues.

Feature request: Add telemetry to the linter, [similar to how the SAM CLI does it](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html):

   - it seems to be opt-out
   - it collects usage data and error reports

**Comment by PatMyron** [comment]
Some other data sources besides direct feedback or telemetry:
https://pypistats.org/packages/cfn-lint
https://pepy.tech/project/cfn-lint
https://github.com/aws-cloudformation/cfn-python-lint/network/dependents
https://github.com/aws-cloudformation/cfn-python-lint/graphs/traffic
https://github.com/search?q=filename:.cfnlintrc&type=Code
https://github.com/search?l=YAML&q=Metadata+cfn-lint+config&type=Code
https://github.com/search?q=cfn-lint+--ignore-checks&type=Code
Same code searches internally as well
