### ISSUE TITLE
Need to validate that resource type is a string

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/cfn-python-lint#1521]
*cfn-lint version: (`cfn-lint --version`)* 0.30.1

*Description of issue.*

![image](https://user-images.githubusercontent.com/5374887/81467963-2c6f5280-9191-11ea-800d-61a8a8445fce.png)

![image](https://user-images.githubusercontent.com/5374887/81468015-97208e00-9191-11ea-8933-6ba116b64f83.png)

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/blob/b788cc9bd3d49ed20d5f2e58602755a0ef37f52c/src/cfnlint/rules/resources/ServerlessTransform.py#L36

https://github.com/aws-cloudformation/cfn-python-lint/blob/2d7ed333e5514896c07a6514eb8a84907b536f29/src/cfnlint/rules/resources/Configuration.py#L63

https://github.com/aws-cloudformation/cfn-python-lint/blob/2d7ed333e5514896c07a6514eb8a84907b536f29/src/cfnlint/rules/resources/Configuration.py#L96

bit of an odd use case I'd rather not check in every rule though, maybe there's somewhere earlier like [`rules/__init__.py`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/rules/__init__.py) this could be caught?

**Comment by miparnisari** [comment]
The code lines you pointed out are all using either `cfn.template.get('Resources', {}).items()` or `cfn.get_resources().items()`. If we can change all instances of the former to the latter, maybe we can make a change within `cfn.get_resources()`:

```python
results = {}
for k, v in resources.items():
    if isinstance(v, dict):
        existing_resource_type = v.get('Type', None)
        if not isinstance(existing_resource_type, six.string_types):
            raise ValueError("A resource type has to be a string")
        if (existing_resource_type in resource_type) or (not resource_type and existing_resource_type is not None):
            results[k] = v

return results
```

**Comment by kddejong** [comment]
@miparnisari I completely agree catching it in `get_resources()`. I tried to make the functions like `cfn.get_resources()` return resources only if they are valid.  No value in returning something if the Type is a number or not even specified.  It should be a safe way to get back "valid" resources that any rule or even other core functionality can use.
