### ISSUE TITLE
AWS::Serverless::Api resource throws error

### ISSUE THREAD

**Issue by ben-elsen** [aws-cloudformation/cfn-python-lint#1534]
**cfn-lint version:** 0.31.1

**Description of issue.**
I have a AWS::Serverless::Api resource that is formatted like the documentation (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html & https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiusageplan.html#sam-property-api-apiusageplan--examples) and everything deploys well to AWS but the linter gives an **error**:

[Serverless IDE] W3005: Obsolete DependsOn on resource (ApiGateway), dependency already enforced by a "Ref" at Resources/ApiGatewayUsagePlan/Properties/ApiStages/0/ApiId/Ref

**The template is:**
```Resources:
  #############################################################
  # The api config
  ############################################################
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
          Quota:
            Limit: 500
            Period: MONTH
          Throttle:
            BurstLimit: 100
            RateLimit: 50```

**Comment by PatMyron** [comment]
Thanks for the template and warning message. We've had quite a few recent similar issues with code generated by the [`AWS::Serverless` transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html) failing rules:
https://github.com/aws-cloudformation/cfn-python-lint/issues/1265
https://github.com/aws-cloudformation/cfn-python-lint/issues/1522

[Raising an issue in their repository](https://github.com/awslabs/serverless-application-model/issues/new) and/or ignoring with something like `--ignore-checks W3005` is probably the best advice I have for now unfortunately

**Comment by ben-elsen** [comment]
Hi @PatMyron, 
Thanks for the advice!

**Comment by stfsy** [comment]
Everyone that is coming across via google, trying to fix linting issues caused by the transformation: When ussing `saml validate` you cannot passt `--ignore-checks W3005` because it's not a valid parameter. 

However, you can follow https://repost.aws/questions/QUct-YwHg9S7u_T8_eLfDwsA/ignore-warnings-from-sam-validate-lint to ignore checks with a `.cfnlintrc.yaml` file.
