### ISSUE TITLE
AWS::Serverless::StateMachine.Definition errors, requiring either Definition or DefinitionUri

### ISSUE THREAD

**Issue by TheDanBlanco** [aws-cloudformation/cfn-python-lint#1575]
*cfn-lint version: (`cfn-lint --version`)*
0.33.0

*Description of issue.*
when creating an AWS::Serverless::StateMachine resource with only a `Role` and a `Definition` property cfn-lint returns that either a `Definition` or a `DefinitionUri` must be present, but not both.

the exact error:
> E0001 Error transforming template: Resource with id [StepFunctionProcessFlow] is invalid. Specify either 'Definition' or 'DefinitionUri' property and not both.
template.yaml:1:1

minimal reproduction template:

```AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources: 
  StepFunctionProcessFlow:
    Type: AWS::Serverless::StateMachine
    Properties:
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/SAMPLE_ROLE
      Definition: 
        StartAt: Register
        States:
          Register:
            Type: Task
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SAMPLE_FUNCTION
            End: True
```

docs: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html#sam-statemachine-definitionuri

specifically, 

> One of Definition or DefinitionUri must be provided. 

version tested: 0.33.0, with `cfn-lint -u` called beforehand

**Comment by PatMyron** [comment]
Hey @TheDanBlanco 👋

Could you run `pip3 show aws-sam-translator | grep 'Version'` to make sure you have 1.24.0+?

and see if it still occurs after `pip3 install aws-sam-translator --upgrade` if not?

**Comment by TheDanBlanco** [comment]
hey @PatMyron! please send everyone at cfn my regards.

`$ pip3 show aws-sam-translator`
Version: 1.24.0

**Comment by PatMyron** [comment]
think the error is being thrown from the Serverless transform itself here:

https://github.com/awslabs/serverless-application-model/blob/153e06b2b0240d1ba37fc46e99324ddb28ad09c1/samtranslator/model/stepfunctions/generators.py#L110

but not encountering the same error when submitting the template to CloudFormation itself
so wondering if any of the Linter code here is causing it be thrown..

https://github.com/aws-cloudformation/cfn-python-lint/blob/67c78bded4490cc0aea9c9899fe94cae037a8193/src/cfnlint/transform.py#L82-L89

**Comment by kddejong** [comment]
Looks like @PatMyron tracked it down.  Missed this scenario when adjusting the code to handle the local file feature of SAM that was recently added.
