### ISSUE TITLE
Document exit codes

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/cfn-python-lint#1587]
Document exit codes on the README. Related to https://github.com/aws-cloudformation/cfn-python-lint/issues/1586#issuecomment-642989484

**Comment by PatMyron** [comment]
maybe a link in [`docs/rules.md`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md)?

the README is a bit overwhelming as-is

**Comment by miparnisari** [comment]
> the README is a bit overwhelming as-is

true, but I don't like jumping around between files to read documentation
