### ISSUE TITLE
Feature Request: List by rules by tag

### ISSUE THREAD

**Issue by lingrlongr** [aws-cloudformation/cfn-python-lint#1610]
#### Feature request
 
It seems a `CloudFormationLintRule`'s `tags` are only used for when generating [documentation](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md).  How about a feature where if we did something like:

    cfn-lint --list [ <tag>, <tagN> ]

... we could filter the results by rule tag.

Usage would look like:

    cfn-lint --list              # all rules
    cfn-lint --list s3           # all rules tagged with s3
    cfn-lint --list s3 ec2       # all rules tagged with s3 or ec2

**Comment by kddejong** [comment]
as the list of rules continues to grow this could be a helpful feature.

**Comment by PatMyron** [comment]
Usually just search https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md itself
Also helps in case any tags are missing as well
Definitely want to continue improving that documentation though: (https://github.com/aws-cloudformation/cfn-python-lint/pull/1374, https://github.com/aws-cloudformation/cfn-python-lint/pull/1517, https://github.com/aws-cloudformation/cfn-python-lint/pull/1519, https://github.com/aws-cloudformation/cfn-python-lint/issues/1587, https://github.com/aws-cloudformation/cfn-python-lint/issues/1641, general formatting)
