### ISSUE TITLE
The Cloudformation Linter Language Server server crashed 5 times

### ISSUE THREAD

**Issue by DaltJM** [aws-cloudformation/cfn-python-lint#1611]
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (c:\Users\ic3yt\.vscode\extensions\kddejong.vscode-cfn-lint-0.12.2\server\out\server.js:198:28)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Info  - 2:23:32 PM] Connection to server got closed. Server will restart.
Settings have been updated...
Settings: {"cfnLint":{"enableAutocomplete":true,"validateUsingJsonSchema":false,"path":"cfn-lint","appendRules":[],"ignoreRules":[],"overrideSpecPath":""}}
Determined this file is a CloudFormation Template. file:///c%3A/Users/ic3yt/Projects/bc_cloudformation_projects/Bastion.yml. Found the string AWSTemplateFormatVersion
Running... cfn-lint --format,json,--,"c:\Users\ic3yt\Projects\bc_cloudformation_projects\Bastion.yml"
'cfn-lint' is not recognized as an internal or external command,
operable program or batch file.

child process exited with code 1 and signal null
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (c:\Users\ic3yt\.vscode\extensions\kddejong.vscode-cfn-lint-0.12.2\server\out\server.js:198:28)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[Error - 2:23:32 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by PatMyron** [comment]
The CloudFormation Linter needs to be installed separately in addition to installing the [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint):
`pip3 install cfn-lint --upgrade`

**Comment by DaltJM** [comment]
Thanks for the reply. Unfortunately it seems to already be up to date.

`C:\Windows\system32>pip3 install cfn-lint --upgrade
Requirement already up-to-date: cfn-lint in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (0.33.2)
Requirement already satisfied, skipping upgrade: junit-xml~=1.9 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cfn-lint) (1.9)
Requirement already satisfied, skipping upgrade: jsonschema~=3.0 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cfn-lint) (3.2.0)
Requirement already satisfied, skipping upgrade: pyyaml; python_version != "3.4" in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cfn-lint) (5.3.1)
Requirement already satisfied, skipping upgrade: six~=1.11 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cfn-lint) (1.15.0)
Requirement already satisfied, skipping upgrade: aws-sam-translator>=1.25.0 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cfn-lint) (1.25.0)
Requirement already satisfied, skipping upgrade: jsonpatch; python_version != "3.4" in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cfn-lint) (1.26)
Requirement already satisfied, skipping upgrade: networkx~=2.4; python_version >= "3.5" in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cfn-lint) (2.4)
Requirement already satisfied, skipping upgrade: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\site-packages (from jsonschema~=3.0->cfn-lint) (41.2.0)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from jsonschema~=3.0->cfn-lint) (0.16.0)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from jsonschema~=3.0->cfn-lint) (19.3.0)
Requirement already satisfied, skipping upgrade: boto3~=1.5 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from aws-sam-translator>=1.25.0->cfn-lint) (1.14.12)
Requirement already satisfied, skipping upgrade: jsonpointer>=1.9 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from jsonpatch; python_version != "3.4"->cfn-lint) (2.0)
Requirement already satisfied, skipping upgrade: decorator>=4.3.0 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from networkx~=2.4; python_version >= "3.5"->cfn-lint) (4.4.2)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from boto3~=1.5->aws-sam-translator>=1.25.0->cfn-lint) (0.10.0)
Requirement already satisfied, skipping upgrade: botocore<1.18.0,>=1.17.12 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from boto3~=1.5->aws-sam-translator>=1.25.0->cfn-lint) (1.17.12)
Requirement already satisfied, skipping upgrade: s3transfer<0.4.0,>=0.3.0 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from boto3~=1.5->aws-sam-translator>=1.25.0->cfn-lint) (0.3.3)
Requirement already satisfied, skipping upgrade: python-dateutil<3.0.0,>=2.1 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from botocore<1.18.0,>=1.17.12->boto3~=1.5->aws-sam-translator>=1.25.0->cfn-lint) (2.8.1)
Requirement already satisfied, skipping upgrade: urllib3<1.26,>=1.20; python_version != "3.4" in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from botocore<1.18.0,>=1.17.12->boto3~=1.5->aws-sam-translator>=1.25.0->cfn-lint) (1.25.9)
Requirement already satisfied, skipping upgrade: docutils<0.16,>=0.10 in c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from botocore<1.18.0,>=1.17.12->boto3~=1.5->aws-sam-translator>=1.25.0->cfn-lint) (0.15.2)`

**Comment by PatMyron** [comment]
Does `cfn-lint` work on the command line? Think PATH might need to be updated if not

**Comment by DaltJM** [comment]
It says it's not a recognized command. I'm not exactly sure how to update the path/where it should go.

**Comment by PatMyron** [comment]
The directory that the `cfn-lint` command is in, `c:\users\ic3yt\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages`, can be appended to [PATH](https://en.wikipedia.org/wiki/PATH_(variable)) like so:
https://stackoverflow.com/questions/9546324/adding-a-directory-to-the-path-environment-variable-in-windows

**Comment by DaltJM** [comment]
Thanks for your help, it's working now :)
