### ISSUE TITLE
Is cfn-lint==0.34.0 retracted?

### ISSUE THREAD

**Issue by dazza-codes** [aws-cloudformation/cfn-python-lint#1624]
```
$ poetry update
Updating dependencies
Resolving dependencies... (8.9s)


Package operations: 0 installs, 16 updates, 0 removals

  - Updating cfn-lint (0.33.2 -> 0.34.0)

[EnvCommandError]
Command ['/opt/conda/envs/jupiter-schema/bin/pip', 'install', '--no-deps', '-U', 'cfn-lint==0.34.0'] errored with the following return code 1, and output: 
ERROR: Could not find a version that satisfies the requirement cfn-lint==0.34.0 (from versions: 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.10, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.5, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.14.1, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.21.4, 0.21.5, 0.21.6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.23.5, 0.24.0, 0.24.1, 0.24.2, 0.24.3, 0.24.4, 0.24.5, 0.24.6, 0.24.7, 0.24.8, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 0.25.5, 0.25.7, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.27.0, 0.27.1, 0.27.2, 0.27.3, 0.27.4, 0.27.5, 0.28.0, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.29.0, 0.29.1, 0.29.2, 0.29.3, 0.29.4, 0.29.5, 0.29.6, 0.30.1, 0.31.0, 0.31.1, 0.32.0, 0.32.1, 0.33.0, 0.33.1, 0.33.2)
ERROR: No matching distribution found for cfn-lint==0.34.0
```

pypi web page indicates 0.33.x is the latest release.

moto depends on it
```
moto 1.3.14 A library that allows your python tests to easily mock out the boto library
|-- cfn-lint >=0.4.0
```

Somehow `poetry` finds the latest version to be `0.34.0` but it cannot actually install it.

As a temporary work-around, a prior version can be added explicitly as a dependency, i.e.
```
poetry add -D cfn-lint==0.33.2
```

**Comment by willbackslash** [comment]
+1 I have the same problem, I cant install the v0.34.0 and it's a subdependency of `moto`

**Comment by PatMyron** [comment]
It was intended to be released today and not intended to be retracted, but there seems to be some PyPI issue today:

https://travis-ci.com/github/aws-cloudformation/cfn-python-lint/jobs/361353841#L2008
https://pypi.org/project/cfn-lint/
https://pypi.org/project/cfn-lint/0.34.0/
```bash
$ pip3 install cfn-lint --upgrade
Requirement already up-to-date: cfn-lint in ./src (0.33.2)
```

**Comment by kddejong** [comment]
Looks like it is updated now.  Is everything working @dazza-codes

**Comment by Metalkiler** [comment]
My package still says the same if you check https://pypi.org/simple/cane/#description

Although I released a cane2.0.0 but it is saying that not exists

**Comment by dazza-codes** [comment]
Sorry, not working yet.  Tested by removing an explicit dependency on the previous release and tried a `poetry update` with the same results; cannot install `0.34.0` yet.  Sounds like this is a temporary pypi glitch that will soon resolve.  It's fine by me to close this issue whenever a confirmed install works.  Looks like the community is finding this issue and maybe the workaround is useful in the meantime.  Cheers.

**Comment by willbackslash** [comment]
It's working for me, I have no problem if you close ir @dazza-codes
