### ISSUE TITLE
E[3001] : Invalid Property resources/<function name>/Properties/FileSystemConfigs

### ISSUE THREAD

**Issue by mantragya** [aws-cloudformation/cfn-python-lint#1663]
*cfn-lint version: (`cfn-lint --version`)*
0.33.2
*Description of issue.*
Creating AWS::Serverless::Function which reads files from EFS system.
When I use FilesystemCofigs inside my server less resource to specify access point arn  i get below warning .
E[3001] : Invalid Property resources/<function name>/Properties/FileSystemConfigs

**Comment by mantragya** [comment]
Let me know if you need more information.

**Comment by mantragya** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/API_FileSystemConfig.html

**Comment by PatMyron** [comment]
[should be in the latest release](https://github.com/aws-cloudformation/cfn-python-lint/issues/1598#issuecomment-658275750):

`pip3 install cfn-lint --upgrade`
