### ISSUE TITLE
6 components of AWS Image builder

### ISSUE THREAD

**Issue by adnanalvee** [aws-cloudformation/cfn-python-lint#1666]
*cfn-lint version: (`cfn-lint --0.14`)*

*Description of issue.*

Cfn-lint needs to support 6 of these components of AWS image builder.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ImageBuilder.html

Getting 'unspported' type error

**Comment by PatMyron** [comment]
Upgrading picks up newer CloudFormation types:
`pip3 install cfn-lint --upgrade`

alternatively have an [online demo](https://github.com/PatMyron/cfn-lint-online) that's always up-to-date if that helps
