### ISSUE TITLE
Recursive lint ignores templates in root directory

### ISSUE THREAD

**Issue by szbmarton** [aws-cloudformation/cfn-python-lint#1676]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.35.0

*Description of issue.*
Recursive searching is not woring as expected:
When I run command `cfn-lint path/**/*.yaml`, root directory is ignored, only templates in subdirectories are linted.

This can be reproduced by creating the following directory structure for example:
path/template1.yaml
path/dir1/template2.yaml
path/dir2/template3.yaml

This way only template2 and template3 will be linted, and template1 is ignored.

I think recursive='True' parameter is missing from python glob configuration.

**Comment by PatMyron** [comment]
Which Python version are you using?

Look supported only for [Python 3.5+](https://github.com/aws-cloudformation/cfn-python-lint/issues/546), which covers [almost all installations](https://pypistats.org/packages/cfn-lint) (and others deprecating soon: https://github.com/aws-cloudformation/cfn-python-lint/issues/1291, https://github.com/aws-cloudformation/cfn-python-lint/pull/1337)

https://github.com/aws-cloudformation/cfn-python-lint/blob/04c1a4b87eecfa8568bc95e533195a6262eb30a3/src/cfnlint/config.py#L572-L576

**Comment by szbmarton** [comment]
I use Python 3.6:

`python3 --version`
Python 3.6.9

`pip3 show cfn-lint`
Name: cfn-lint
Version: 0.35.0
Summary: Checks CloudFormation templates for practices and behaviour that could potentially be improved
Home-page: https://github.com/aws-cloudformation/cfn-python-lint
Author: kddejong
Author-email: kddejong@amazon.com
License: MIT no attribution
Location: /home/szbmarton/.local/lib/python3.6/site-packages
Requires: jsonschema, jsonpatch, pyyaml, networkx, junit-xml, importlib-resources, aws-sam-translator, six
Required-by:

**Comment by PatMyron** [comment]
Could you try [`shopt -s globstar`](https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html#:~:text=globstar) if using bash?

**Comment by szbmarton** [comment]
Thanks, it works now.
