### ISSUE TITLE
E3502 - PolicyDocument max size

### ISSUE THREAD

**Issue by IvanBlanquez** [aws-cloudformation/cfn-python-lint#1679]
*cfn-lint version: (`0.35.1`)*

*Description of issue.*

Using the resource `Type: "AWS::IAM::ManagedPolicy"` when I define a PolicyDocument property cnf-lint shows me the message *"Role trust policy JSON text cannot be longer than 6144 characters [E3502]"*. But PolicyDocument can has up to 131072 characters as [AWS::IAM::Role Policy documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-policy.html#cfn-iam-policies-policydocument) defines.

**Comment by IvanBlanquez** [comment]
I've just find that the limits for managed policy still being 6144 [reference_iam-quotas](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html). So maybe I don't understand that information at all

**Comment by PatMyron** [comment]
Code here btw:
https://github.com/aws-cloudformation/cfn-python-lint/blob/6cce9222c89056f1546f6fee068ce6dc9dfa394e/src/cfnlint/data/ExtendedSpecs/all/03_value_types/aws_iam.json#L153
