### ISSUE TITLE
Question: documentation that backs the rules and "best practice"

### ISSUE THREAD

**Issue by gunzy83** [aws-cloudformation/cfn-python-lint#1730]
*cfn-lint version: 0.37.1*

*Question about documentation that some rules are based on.*

Hi, 

Long time cloudformation user here (since the old JSON times), been using other tools for linting and validation for a while and just integrating this into our Ansible playbooks that drive our template generation and deployments (via a custom module).  So far so good, integration has been very easy and configurable :+1: . Most of the rules when it comes to documented types, functions etc make sense but I have a question about how I go about finding whether or not a Warning is worth worrying about or not for things that appear rather arbitrary and made up. The example I just ran up against is this rule:

* W3010 - Availability Zone Parameters should not be hardcoded

While I would like an answer why this actually matters (it is hardcoded because we have template generation and use Parameters for control without needing a template. I shouldn't need to make a parameter for each one when the value is always going to be the same), I am more interested in finding out where I can find the documentation that the rules are based on so I understand why they are calling these things out. If I understood the "why", I can make a more informed choice to ignore the warning in my config.

Thanks in advance.

Ross

**Comment by PatMyron** [comment]
[Documentation on our rule levels](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md#rule-levels) and [discussion](https://github.com/aws-cloudformation/cfn-python-lint/issues/19)

Also a specific [`W3010` discussion](https://github.com/aws-cloudformation/cfn-python-lint/issues/886): that rule is to help templates be reusable in multiple regions, but feel free to [`--ignore-checks`](https://github.com/aws-cloudformation/cfn-python-lint#parameters) based on your own needs

**Comment by gunzy83** [comment]
On `W3010`, that makes sense. I found "best practice" documentation and many of the recommendations do not make sense when templating (we gain our portability via Jinja). The message on some of the rules (like this one) are tough to trace back to the "why" and best practice is a loaded term IMO (highly subjective and situational). I will refer to the doco in future and try to line up the intention and we can decide how and where to ignore or configure rules.

Thanks.
