### ISSUE TITLE
Check the policy size

### ISSUE THREAD

**Issue by pruthvirajksuresh** [aws-cloudformation/cfn-python-lint#1762]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.38.0

*Description of issue.*

cfn-lint 0.38.0
 
Please provide as much information as possible:

https://github.com/docker/docker.github.io/issues/5815

if the policy is too long the linter will pass the template but the cloudformation will fail it. the max charters for policy is not verified.

**Comment by PatMyron** [comment]
Which property type? Think we have that covered for some property types at least:
https://github.com/aws-cloudformation/cfn-python-lint/blob/1f393051c70c920d58d7337608c067530843350c/src/cfnlint/data/ExtendedSpecs/all/03_value_types/aws_iam.json#L148-L150

**Comment by pruthvirajksuresh** [comment]
hi pat, i am talking about the managed policy and the template is in YAML format.  i got the below error 
<img width="671" alt="Screen Shot 2020-11-02 at 1 02 41 PM" src="https://user-images.githubusercontent.com/38190949/97908048-c3b1fe80-1d0b-11eb-81c3-2c1217415e51.png">

**Comment by kddejong** [comment]
It could be that this policy is wrapped with a Sub or has a Ref in it.  That makes judging this harder.  I tried following the issue to the actual code but I can't seem to get there. @pruthvirajksuresh can you provide any additional insights on that policy.  Whats the resource type and a understanding of that policy in code (is there a Fn::Sub or Fn::Join or a Ref/GetAtt inside of it)?

**Comment by pruthvirajksuresh** [comment]
hi @kddejong , yes the policies are being created with the name which uses Ref and Sub as well
