### ISSUE TITLE
Newline in rule output for W2031 breaks parseable format

### ISSUE THREAD

**Issue by direvus** [aws-cloudformation/cfn-python-lint#1822]
https://github.com/aws-cloudformation/cfn-python-lint/blob/e6b5e4f8863ba64cf6fbe2a3e36c113e65c200a6/src/cfnlint/rules/parameters/AllowedPattern.py#L64 and again on L72 embeds a newline character in the message from rule W2031.

This breaks the output in `-f parseable` mode, which is line based.

I think we should make 2 changes:

- remove newlines from all messages produced by rules, and
- modify the behaviour of `-f parseable` to replace newlines in rule messages with spaces.

PR to follow.

**Comment by PatMyron** [comment]
[recommend against the `parseable` format btw](https://github.com/aws-cloudformation/cfn-python-lint/issues/1467#issuecomment-687864814)

**Comment by direvus** [comment]
> [recommend against the `parseable` format btw](https://github.com/aws-cloudformation/cfn-python-lint/issues/1467#issuecomment-687864814)

Yeah, the issue I've raised is certainly not the only problem with "parseable".  It's pretty depressing that it doesn't bother to escape or quote colon characters within the fields.  But, unless you want to formally deprecate it, "parseable" is still one of the supported formats, so it should work, to some extent.  I feel that my PR is an easy win that moves it a little closer towards useful.
