### ISSUE TITLE
 Add GP3 As a Valid Volume Type

### ISSUE THREAD

**Issue by andrew-glenn** [aws-cloudformation/cfn-python-lint#1829]
_Courtesy redirect from https://github.com/aws-quickstart/taskcat/issues/625_

(I suspect the upstream specs are not updated to support the new `gp3` volume types, yet. )

>The Linter does not recognize GP3 as a valid volume type. "You must specify a valid value for VolumeType (gp3). Valid values are ["gp2", "io1", "io2", "sc1", "st1", "standard"]"

**Comment by PatMyron** [comment]
released in [`cfn-lint 0.43.0`](https://github.com/aws-cloudformation/cfn-python-lint/releases/tag/v0.43.0):
[`pip3 install cfn-lint --upgrade`](https://github.com/aws-cloudformation/cfn-python-lint/pull/1804)
