### ISSUE TITLE
Ignore Rule at the Command line and Template Level at the same time

### ISSUE THREAD

**Issue by josjaf** [aws-cloudformation/cfn-python-lint#1830]
*cfn-lint version: (`cfn-lint --version`)* 0.42.0

*Description of issue. When specifying cfn -i at the command line, cfn-lint does not look for additional ignore rules inside of the template. Is this expected behavior? Is there a way to the tool to detect command line and template level ignores at the same time. 

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by kddejong** [comment]
@PatMyron we have had this request a few times.  I'm thinking we could add a merge configuration  parameter?  This would only apply to lists of course.  Thoughts?

**Comment by jonathanmorley** [comment]
Looks to be addressed by https://github.com/aws-cloudformation/cfn-python-lint/pull/1915

**Comment by kddejong** [comment]
@jonathanmorley is correct.  This is now available using the `merge-configs` option.
