### ISSUE TITLE
Add AWS SSO Permission Set inline policy to IAM policy checking

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cfn-python-lint#1862]
E2507 "Check if IAM Policies are properly configured" should add `AWS::SSO::PermissionSet.InlinePolicy` to its list of policy properties to check.

https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/rules/resources/iam/Policy.py#L35

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html#cfn-sso-permissionset-inlinepolicy

**Comment by benkehoe** [comment]
So prompt! ❤❤❤

**Comment by kddejong** [comment]
Thanks for submitting the issue.  I also discovered another issue along the way so much appreciated.

This will be included in the next release which should be out this week.
