### ISSUE TITLE
Lambda maximum MemorySize is now 10,240MB (from 3,008MB)

### ISSUE THREAD

**Issue by nayaverdier** [aws-cloudformation/cfn-python-lint#1865]
Reference: https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-supports-10gb-memory-6-vcpu-cores-lambda-functions/

Would imagine that just this value needs to be updated, I can create a PR for that if necessary:
https://github.com/aws-cloudformation/cfn-python-lint/blob/ed0bdf79816aa38c6262bcbbf2dc04d08df79650/src/cfnlint/data/ExtendedSpecs/all/03_value_types/aws_lambda.json#L6

**Comment by PatMyron** [comment]
whoops, missed this duplicate in https://github.com/aws-cloudformation/cfn-python-lint/pull/1858

**Comment by kddejong** [comment]
Cleaned up the duplicate in that PR.  Also this should be fixed in [v0.44.3](https://github.com/aws-cloudformation/cfn-python-lint/releases/tag/v0.44.3)
