### ISSUE TITLE
Omit rule for the next line

### ISSUE THREAD

**Issue by HFR1994** [aws-cloudformation/cfn-python-lint#1874]
*cfn-lint version: 0.44.4*

*Description of issue.*

Please provide as much information as possible:
* Feature request:
  * I have included some Macros that expand the CloudFormation capabilities of my template for [example the Explode Function](https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/services/CloudFormation/MacrosExamples/Explode)
  * When I write my file, I do something like:

```
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM template with a simple API definition
Transform: 
  - Explode
  - AWS::Serverless-2016-10-31

Mappings:

  EnvironmentsMap:
    Dev:
      Environment: Test
      Prefix: "-test"
    Staging:
      Environment: Staging
      Prefix: "-staging"
    Prod:
      Environment: Production
      Prefix: ""

Resources:

  ApiGateway:
    ExplodeMap: EnvironmentsMap
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: apigateway.yaml
      Parameters:
         StageName: "!Explode Environment"
```

Which causes a linting error on the **ExplodeMap (Rule E3001)** and **EnvironmentsMap (W7001)** key definition I don't want to disable the entire check using:

```
   ....
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
          - W7001
   ...
```

I just want to omit it for a specific line. As a feature can we add a line comment to disable the rule? Something like:

```
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM template with a simple API definition
Transform: 
  - Explode
  - AWS::Serverless-2016-10-31

Mappings:

  # cfn-lint: ignore-check W007
  EnvironmentsMap:
    Dev:
      Environment: Test
      Prefix: "-test"
    Staging:
      Environment: Staging
      Prefix: "-staging"
    Prod:
      Environment: Production
      Prefix: ""

Resources:

  ApiGateway:
    # cfn-lint: ignore-check E001
    ExplodeMap: EnvironmentsMap
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: apigateway.yaml
      Parameters:
         StageName: "!Explode Environment"
```
Where if you would like to disable multiple values you can do something like:

`  # cfn-lint: ignore-check W007, E001`

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by PatMyron** [comment]
tracking in https://github.com/aws-cloudformation/cfn-python-lint/issues/113
