### ISSUE TITLE
AttributeError: _DistInfoDistribution__dep_map when pip3 install cfn-lint 

### ISSUE THREAD

**Issue by ahtsan** [aws-cloudformation/cfn-python-lint#1880]
*cfn-lint version: (`cfn-lint --version`)*
N/A

*Description of issue.*
I was trying to install cfn-lint in a AWS CodeBuild project. When running `pip3 install cfn-lint`, I got the following error:

![image](https://user-images.githubusercontent.com/10270515/106319168-ddd57d00-6225-11eb-9243-854ac1e81f92.png)

Do you have any advise?

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by PatMyron** [comment]
https://github.com/jupyter/notebook/issues/2605
Could you try upgrading `pip` and `setuptools` before installing `cfn-lint`?
If that doesn't work, could you include your CodeBuild snippet?

**Comment by ahtsan** [comment]
Got this:
![image](https://user-images.githubusercontent.com/10270515/106340908-2f92fd00-6250-11eb-8425-e742d36bb2f0.png)

The snippet is basically using the image `codebuild.LinuxBuildImage.UBUNTU_14_04_NODEJS_10_1_0` and executing the following commands:
```
[
 "apt-add-repository ppa:brightbox/ruby-ng",
 "apt update",
 "apt install -y python3-pip",
 "pip3 install --upgrade setuptools",
 "pip3 install cfn-lint",
 "apt install -y ruby2.5 ruby2.5-dev",
 "gem install cfn-nag"
]

```

**Comment by ahtsan** [comment]
and for `pip3 install --upgrade pip`

![image](https://user-images.githubusercontent.com/10270515/106341554-8c8fb280-6252-11eb-91ae-07f049ee6dd4.png)

**Comment by ahtsan** [comment]
Using python 3.6 resolves the issue.
