### ISSUE TITLE
option to ignore check W2001: Parameter not used for specific parameters in the template file

### ISSUE THREAD

**Issue by tekdj7** [aws-cloudformation/cfn-python-lint#1889]
*cfn-lint version: (`cfn-lint --version`)*
0.44.6

*Description of issue.*
option to ignore check `W2001: Parameter not used` for specific parameters in the template file

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-python-lint/issues/113 should more generally cover this if implemented, tracking there
