### ISSUE TITLE
ListenerRule's ListernerArn complains about usage of Fn::ImportValue

### ISSUE THREAD

**Issue by svrx** [aws-cloudformation/cfn-python-lint#1890]
*cfn-lint version: 0.44.5*

*Description of issue.*
`
```
ServiceListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ...
      ListenerArn: 
        Fn:ImportValue: !Sub "${InfraStackName}-WebLoadBalancerListenerArn"
      ...
```

Throws following error:
`[cfn-lint] E3002: Property Resources/ServiceListenerRule/Properties/ListenerArn has an illegal function Fn:ImportValue`

Is this a real limitation? 
Where is it documented?

**Comment by PatMyron** [comment]
Looks like [`Fn::ImportValue`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html) is missing one `:` in that snippet
