### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by mikecee** [aws-cloudformation/cfn-python-lint#192]
While learning the codebase I've been working on some trivial PRs including spelling and the like.  It occurred to me that it's not _that_ much more effort [hah!] to do a full internationalisation of all the output messages.  Is there any appetite for this?  I'm happy to do the work but understand that it's not always desirable.

## Advantages:

* Perhaps increase contributions to and  awareness of `cfn-lint`
* Assist non-English speakers to improve their template quality

## Disadvantages:

The usual:

* Code uglification.  For many people, myself included, having `_()` plastering code makes it harder to _read_ the code.
* Having to maintain the message tables is an added overhead.  Obviously the default of returning the string for an unmatched key e.g. `_('my new message')` helps here, but still...
* Productivity loss / contributor annoyance.   See above points.

Discussion welcome

**Comment by cmmeyer** [comment]
Interesting offer! I like the idea of localization/internationalization but I'm of two minds:

1. Not sure if our contributor base has hit the critical mass necessary to accept the overhead
2. But it's only going to get more complicated as we add more rules

Other opinions?

**Comment by fatbasstard** [comment]
Well, IT is worldwide pretty "English" oriented, so Internationalisation of the core "IT" tooling around is not (or should not) be a big issue, although I agree it's added value and might help with the adoption rate.

But it's the downsides that bother me, it adds complexity and maintenance to the codebase. But not only in the codebase itself, but this also (possibly) affect external code, for instance when using custom code.

**Comment by kddejong** [comment]
@mikecee I absolutely agree that the error messages need a little work.  I would bet some are not easy to read for non English speakers.   I know certain teams are lucky enough to have a group of people looking into this type of stuff.  If you see any phrases or poor grammar choices that we can fix to make rule descriptions more readable please let us know or submit a pull request.

I would be curious what it would take to provide such a feature but I'm with @cmmeyer on making sure we hit a more critical mass before we accept the overhead.

**Comment by PatMyron** [comment]
Unfortunately, we won't have the resources to maintain manual translations for the foreseeable future, so I'm going to close this issue

Feel free to contribute error message improvements in any case where messages are unnecessarily difficult to translate from English using another tool or understand for non native English speakers. I'll also reach out to our tech writers to see if there are any guidelines or tools to help make our English messages more accessible
