### ISSUE TITLE
'cfn-lint' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by nareshNishad** [aws-cloudformation/cfn-python-lint#1964]
### Installing cfn-lint command run successfully but running cfn-lint gives an error.

`pip install cfn-lint --user

  Collecting cfn-lint
  Using cached cfn_lint-0.48.1-py3-none-any.whl (5.9 MB)
Requirement already satisfied: jsonschema~=3.0 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from cfn-lint) (3.2.0)
Requirement already satisfied: six>=1.11 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from cfn-lint) (1.15.0)
Requirement already satisfied: junit-xml~=1.9 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from cfn-lint) (1.9)
Requirement already satisfied: jsonpatch in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from cfn-lint) (1.32)
Requirement already satisfied: pyyaml in c:\python39\lib\site-packages (from cfn-lint) (5.4.1)
Requirement already satisfied: aws-sam-translator>=1.34.0 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from cfn-lint) (1.35.0)
Requirement already satisfied: networkx~=2.4 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from cfn-lint) (2.5)
Requirement already satisfied: boto3~=1.5 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from aws-sam-translator>=1.34.0->cfn-lint) (1.17.41)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from boto3~=1.5->aws-sam-translator>=1.34.0->cfn-lint) (0.3.6)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from boto3~=1.5->aws-sam-translator>=1.34.0->cfn-lint) (0.10.0)
Requirement already satisfied: botocore<1.21.0,>=1.20.41 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from boto3~=1.5->aws-sam-translator>=1.34.0->cfn-lint) (1.20.41)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from botocore<1.21.0,>=1.20.41->boto3~=1.5->aws-sam-translator>=1.34.0->cfn-lint) (2.8.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from botocore<1.21.0,>=1.20.41->boto3~=1.5->aws-sam-translator>=1.34.0->cfn-lint) (1.26.4)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from jsonschema~=3.0->cfn-lint) (0.17.3)
Requirement already satisfied: setuptools in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from jsonschema~=3.0->cfn-lint) (54.2.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from jsonschema~=3.0->cfn-lint) (20.3.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\nareshchandnishad\appdata\roaming\python\python39\site-packages (from networkx~=2.4->cfn-lint) (4.4.2)
Requirement already satisfied: jsonpointer>=1.9 in c:\python39\lib\site-packages (from jsonpatch->cfn-lint) (2.1)
Installing collected packages: cfn-lint
  WARNING: The script cfn-lint.exe is installed in 'C:\Users\NareshChandNishad\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cfn-lint-0.48.1`

**On running version check**

`cfn-lint --version

cfn-lint' is not recognized as an internal or external command,
operable program or batch file.`

**Python version 3.9.2
pip version 21.0.1
system Windows**

**Comment by PatMyron** [comment]
https://en.wikipedia.org/wiki/PATH_(variable)#DOS,_OS/2,_and_Windows

```bash
WARNING: The script cfn-lint.exe is installed in 'C:\Users\NareshChandNishad\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
Consider adding this directory to PATH
```

Can either [append that directory to your `PATH`](https://stackoverflow.com/questions/9546324/adding-a-directory-to-the-path-environment-variable-in-windows) or use the full path of the executable
