### ISSUE TITLE
Unsupported Type AWS::ECS::ClusterCapacityProviderAssociations

### ISSUE THREAD

**Issue by farski** [aws-cloudformation/cfn-python-lint#1968]
I have a template that includes a `AWS::ECS::ClusterCapacityProviderAssociations` resource, and cnf-lint is raising an error on it:

> [cfn-lint] E3001: Invalid or unsupported Type AWS::ECS::ClusterCapacityProviderAssociations for resource ClusterCapacityProviderAssociation in us-east-1

The template and resource are working correctly in `us-east-1`, so I think the error may be a mistake.

**Comment by PatMyron** [comment]
picked up in https://github.com/aws-cloudformation/cfn-python-lint/pull/1939, upgrading should pick this up:

`pip3 install cfn-lint --upgrade`
