### ISSUE TITLE
Outdated Version in Brew

### ISSUE THREAD

**Issue by bernays** [aws-cloudformation/cfn-python-lint#1971]
*cfn-lint version: [0.46.0](https://github.com/aws-cloudformation/cfn-python-lint/releases/tag/v0.46.0)*

**Description of issue:**

When installing cfn-lint via the documented `brew install cfn-lint` you get an outdated version of cfn-lint

**Comment by PatMyron** [comment]
@chenrui333 any ideas?

**Comment by bernays** [comment]
It seems that the `cfn-lint` formula is out of date: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cfn-lint.rb

**Comment by carlocab** [comment]
Please open a pull request to update the formula: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

Thanks!
