### ISSUE TITLE
E3001 Invalid or unsupported Type AWS::SES::ReceiptRuleSet and AWS::SES::ReceiptRule

### ISSUE THREAD

**Issue by ljian266** [aws-cloudformation/cfn-python-lint#2007]
*cfn-lint version: cfn-lint-0.49.1

*Description of issue.*
E3001 Invalid or unsupported Type AWS::SES::ReceiptRuleSet
E3001 Invalid or unsupported Type AWS::SES::ReceiptRule

Please provide as much information as possible:
cfn-lint is failing on valid types.

Cfn-lint uses the [CloudFormation Resource Specifications]These types are valid according to AWS documentation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptrule.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptruleset.html

**Comment by kddejong** [comment]
@ljian266 what region are you validating against?

**Comment by ljian266** [comment]
good point. did not realize cfn-lint was region specific. 
thanks!
