### ISSUE TITLE
Enable repo wiki so we can document errors/warnings

### ISSUE THREAD

**Issue by alexjurkiewicz** [aws-cloudformation/cfn-python-lint#339]
Like the Shellcheck wiki: https://github.com/koalaman/shellcheck/wiki/SC1090

**Comment by cmmeyer** [comment]
Interesting. So is the idea that each rule would link to the wiki page, rather than directly to the rule source in docs?

**Comment by cmmeyer** [comment]
Rules are documented in the generated file https://github.com/awslabs/cfn-python-lint/blob/master/docs/rules.md and linked to from the "Rules" section of the README.md.  

I like this because the documentation is right there as part of the source package.  Are there benefits to breaking this out into a wiki?

**Comment by alexjurkiewicz** [comment]
Context for request: I'd like to add some extra documentation for certain rules.

For example `E2507`'s current documentation is "See if there elements inside an IAM policy are correct". Not helpful! I received an error message from this check that I was using `Version: 2008-10-17`. But there was no explanation why this was a problem. It's also not clear from the linked AWS documentation.

I would like cfn-lint rules to be documented with a rationale and exceptions section, as per the shellcheck wiki.

If the choice is to put this in-repo as markdown documents, that's fine too. I don't like the current file because it's not possible to link to a specific rule.

**Comment by fatbasstard** [comment]
Rule documentation could/should be improved. If Wiki is the way to go: Don't know.

For some the rules that have no clear "original" of the documentation there already is some documentation: https://github.com/awslabs/cfn-python-lint/blob/master/docs/cfn-resource-specification.md

In the general rules documentation that's generated (https://github.com/awslabs/cfn-python-lint/blob/master/docs/rules.md) is also a link to the source

The URL that's connected to the Rule is available, just not outputted everywhere (Formatters)

**Comment by PatMyron** [comment]
Following up on this, individual rule IDs can be linked in the rule documentation like so:
https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md#E1001
