### ISSUE TITLE
Feature request:  Create Homebrew formula for installation on OS X

### ISSUE THREAD

**Issue by matsev** [aws-cloudformation/cfn-python-lint#493]
Homebrew is commonly used to install command line tools on OS X, [awscli](https://formulae.brew.sh/formula/awscli) and [aws-sam-cli](https://github.com/aws/homebrew-tap/blob/master/Formula/aws-sam-cli.rb) being case in point. Thus, it would make sense to also install the CloudFormation Linter using Homebrew.

Related: https://github.com/aws/homebrew-tap/issues/12

**Comment by matsev** [comment]
See also https://github.com/aws/homebrew-tap/pull/26

**Comment by xiaket** [comment]
With 86f473c in place, I think we can close this one now?

**Comment by kddejong** [comment]
Fair. Thanks for pointing that out
