### ISSUE TITLE
State and ExecutionRoleArn required for DLM LifecyclePolicy

### ISSUE THREAD

**Issue by cmmeyer** [aws-cloudformation/cfn-python-lint#563]
*cfn-lint version: (`cfn-lint --version`)*
0.11.0

*Description of issue.*

AWS::DLM::LifecyclePolicy requires State and ExecutionRoleArn on creation per  https://docs.aws.amazon.com/dlm/latest/APIReference/API_CreateLifecyclePolicy.html

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

**Comment by kddejong** [comment]
Labeling Spec Patches for tracking and closing.
