### ISSUE TITLE
Single-subnet ELB detection

### ISSUE THREAD

**Issue by viraptor** [aws-cloudformation/cfn-python-lint#638]
*cfn-lint version: 0.10.3*

*Description of issue.*

When configuring `AWS::ElasticLoadBalancingV2::LoadBalancer`, if you specify only 1 subnet, you get back from AWS:

> 2019-02-05 12:22:39 +1100 Elb AWS::ElasticLoadBalancingV2::LoadBalancer CREATE_FAILED At least two subnets in two different Availability Zones must be specified (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: ...)

This could be covered by a cfn-lint check.

**Comment by cmmeyer** [comment]
Solid rule idea. I'll label this as a new rule until someone picks it up.

Thanks!

**Comment by kddejong** [comment]
I think this becomes a definition in the spec once #759 is merged
