### ISSUE TITLE
Add a cfn-lint validation pipeline to the SAR

### ISSUE THREAD

**Issue by cmmeyer** [aws-cloudformation/cfn-python-lint#661]
cfn_nag recently added a validation pipeline to the Serverless Application Repo. It would be cool to do something similar for cfn-lint.

https://stelligent.com/2018/05/25/serverless-cloudformation-linting-in-aws-codepipeline/

**Comment by PatMyron** [comment]
won't be officially picking this up anytime soon, but would love to see it if anyone else ends up picking this up
