### ISSUE TITLE
Unsupported type AWS::Route53Resolver::ResolverEndpoint

### ISSUE THREAD

**Issue by aap69** [aws-cloudformation/cfn-python-lint#669]
*cfn-lint version: cfn-lint 0.14.1*

*New DNS Resolver type not supported.*

Template Resource Definition:

  Route53ResolverIn:
    Type: AWS::Route53Resolver::ResolverEndpoint
    Properties:
      Direction: INBOUND
      IpAddresses: 
        -
          SubnetId:
            Fn::ImportValue: !Sub "${SharedServicesVPCStackName}-ManagementSubnetAID"
        - 
          SubnetId:
            Fn::ImportValue: !Sub "${SharedServicesVPCStackName}-ManagementSubnetBID"
      Name: !Sub "${ResolverName}-In"
      SecurityGroupIds: 
        - !Ref sgRoute53Resolver
      Tags: 
        - Key: Name
          Value: !Sub "${ResolverName}-In"
        - Key: Project
          Value:
            Ref: ProjectTag
        - Key: Environment
          Value:
            Ref: EnvironmentTag
        - Key: Application
          Value:
            Ref: ApplicationTag

Error Message:

E3001 Invalid or unsupported Type AWS::Route53Resolver::ResolverEndpoint for resource Route53ResolverIn in ap-southeast-2

Documentation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53resolver-resolverendpoint.html

**Comment by fatbasstard** [comment]
Seems like a Spec bug:

It's available in the Specs if `ap-southeast-1`, but not 2. According to AWS it should be available there (https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/)

@cmmeyer Can you validate this?

@aap69 If this is indeed missing in the specs files (let's get it checked by @cmmeyer ) we can create a Spec path to add it.

**Comment by cmmeyer** [comment]
I've cut an internal ticket for this. If it's not a fast fix we can get a patch out as a short term solution.
