### ISSUE TITLE
[Bug] Unhandled error being thrown for !Ref "AWS::Region"

### ISSUE THREAD

**Issue by ScriptMyJob** [aws-cloudformation/cfn-python-lint#705]
*cfn-lint version: (`cfn-lint --version`)*
```
cfn-lint 0.15.0
```

*Description of issue.*

Please provide as much information as possible:
* Template linting issues:
  * Add `!Ref "AWS::Region"` to a template and try to lint it.  I have upgraded to 0.15.0 and verified that this issue is still present.
```
Traceback (most recent call last):
  File "/usr/local/bin/cfn-lint", line 11, in <module>
    load_entry_point('cfn-lint==0.14.0', 'console_scripts', 'cfn-lint')()
  File "/Library/Python/2.7/site-packages/cfnlint/__main__.py", line 37, in main
    args.regions, args.override_spec))
  File "/Library/Python/2.7/site-packages/cfnlint/core.py", line 55, in run_cli
    return run_checks(filename, template, rules, regions)
  File "/Library/Python/2.7/site-packages/cfnlint/core.py", line 161, in run_checks
    if not set(regions).issubset(set(REGIONS)):
TypeError: unhashable type: 'dict_node'
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

**Comment by kddejong** [comment]
I can't seem to reproduce the error.  Are you using a .cfnlintrc file?  That line of the error is related to the `--region` parameter which could have been set in the Metadata, .cfnlintrc, and/or parameters. 
 Seems weird though that it would fail only if `!Ref "AWS::Region"` is included in the template.  

Whatever is causing it we should have caught it though and I'm going to try a few things to try and replicate it.

**Comment by ScriptMyJob** [comment]
Oh you know what... Someone put that in the metadata section of our CloudFormation Template.

🤦‍♂️ 

Thanks @kddejong

**Comment by kddejong** [comment]
It brings up a bunch of good questions though.  We should catch that better and fail cleaner.
