### ISSUE TITLE
E0001 no attribute 'logging' error validating SAM template 

### ISSUE THREAD

**Issue by zaro0508** [aws-cloudformation/cfn-python-lint#714]
*Version*
```
❯❯❯ cfn-lint --version
cfn-lint 0.15.0
```
*Modules*
```
❯❯❯ pip freeze
aws-sam-translator==1.10.0
boto3==1.9.112
botocore==1.12.112
certifi==2019.3.9
cfn-lint==0.15.0
chardet==3.0.4
docutils==0.14
idna==2.8
jmespath==0.9.4
jsonpatch==1.23
jsonpointer==2.0
jsonschema==2.6.0
python-dateutil==2.8.0
PyYAML==3.13
requests==2.21.0
s3transfer==0.2.0
six==1.12.0
urllib3==1.24.1
```

*Description of issue.*
Running cnf-lint on serverless template gives `E0001` error.. 
```
❯❯❯ cfn-lint ./lambdas/**/*.yaml
E0001 Error transforming template: module 'samtranslator.parser.parser' has no attribute 'logging'
./lambdas/rotate-credentials/template.yaml:1:1
```

The template is here: https://github.com/Sage-Bionetworks/aws-infra/blob/master/lambdas/rotate-credentials/template.yaml

This seems like a regression.  It only happen when `aws-sam-translator==1.10.0` is installed.  It does not happen when I replace 1.10.0 with `aws-sam-translator==1.9.1`.

**Comment by fatbasstard** [comment]
Hi!

This is introduced by SAM 1.10 and has already been fixed (https://github.com/aws-cloudformation/cfn-python-lint/pull/702). A new release with this fix will be coming today or tomorrow

**Comment by kddejong** [comment]
Release v0.16.0 was just cut.  This fix is included and will be released shortly.
