### ISSUE TITLE
Continued expansion of the Spec files to include Min/Max

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-python-lint#739]
I would like to propose a continued expansion of the spec files to include Min/Max information

- [x] Min/Max of string
- [x] Min/Max size of a JSON object (example: IAM Policy)
- [x] Min/Max size of a list
- [x] Min/Max of a number

All of these need some level of handling functions (especially conditions).  We can build out the core functionality and then it becomes easier to add additional checks for similar patterns.

**Comment by fatbasstard** [comment]
Love the idea (of course). Maybe we need to restructure the AllowedValues (and/or spec patching definition) a bit in order to support it?

**Comment by kddejong** [comment]
This will be done in the next release.  Closing it as I created this.
