### ISSUE TITLE
E3008 when using GetAtt for Property "Role" of type AWS::Glue::Job

### ISSUE THREAD

**Issue by benlalanes** [aws-cloudformation/cfn-python-lint#744]
*cfn-lint version: 0.16.0*

*Description of issue.*
Getting `E3008` error when providing a valid Role ARN via `Fn:GetAtt` to the `AWS::Glue::Job` resource type:

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
    * https://github.com/benlalanes/glue-cfn-test/blob/master/glue-test.yml
    * Specific Error message for this template is: `E3008 Property "Role" has no valid Fn::GetAtt options at Resources/GlueJob/Properties/Role/Fn::GetAtt`
  * If present, please add links to the (official) documentation for clarification.
    * https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html

**Comment by kddejong** [comment]
I got this one.  According to the API documentation it will take the Role Name or ARN.  I would be curious of the validity of the Names when doing a Path but both should be allowed.

**Comment by benlalanes** [comment]
Awesome, thanks for super quick response! :)
