### ISSUE TITLE
Add PermissionsBoundary support to Globals and Serverless::Function

### ISSUE THREAD

**Issue by cervantek** [aws-cloudformation/cfn-python-lint#760]
SAM now supports Permissions Boundaries in Globals and in AWS::Serverless:::Function. Could you please add support for this?

Currently, cfn-lint 0.17.0 returns one of these errors:

E0001 Error transforming template: Resource with id [FunctionName] is invalid. property PermissionsBoundary not defined for resource of type AWS::Serverless::Function
template.yaml:1:1

E0001 Error transforming template: 'Globals' section is invalid. 'PermissionsBoundary' is not a supported property of 'Function'. Must be one of the following values - ['Handler', 'Runtime', 'CodeUri', 'DeadLetterQueue', 'Description', 'MemorySize', 'Timeout', 'VpcConfig', 'Environment', 'Tags', 'Tracing', 'KmsKeyArn', 'AutoPublishAlias', 'Layers', 'DeploymentPreference']
template.yaml:1:1

**Comment by fatbasstard** [comment]
Which function of SAM is used by `cfn-lint`? The error (`E0001`) comes directly from SAM.  You can find the version by running in debug mode (`cfn-lint -d`)

**Comment by kddejong** [comment]
Looks like this was added in 1.10.0
https://github.com/awslabs/serverless-application-model/blob/v1.10.0/samtranslator/plugins/globals/globals.py#L33

**Comment by cervantek** [comment]
I upgraded to the release from yesterday, 0.17.1, an is is no longer failing the E0001 check. I ran the cfn-lint -d per the suggestion, and I'm not sure what I'm looking for, but do see it is using SAM translator 1.10, which is the release that PermissionsBoundary was added in. So this issue can be closed.
