### ISSUE TITLE
CloudWatchLogGroups are must not duplicated in the Lambda's Events section

### ISSUE THREAD

**Issue by daisuke-awaji** [aws-cloudformation/cfn-python-lint#773]
*cfn-lint version: cfn-lint 0.9.0*

*Description of issue.*

![image](https://user-images.githubusercontent.com/20736455/55238033-e1d59400-5276-11e9-9619-13c308678d86.png)

In this configuration, Lambda for log analysis (LogSubscriptionFunction in this figure) subscribes and processes multiple Lambda logs output to CloudWatchLogs.
CloudFormation templates can be described as follows.

```.yaml
  LogSubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: subscription_function/build/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        FunctionALogGroup:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: !Ref FunctionALogGroup
            FilterPattern: ""
        FunctionBLogGroup:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: !Ref FunctionALogGroup # <--- log group is duplicated !!
            FilterPattern: ""
```

If the log group is duplicated in the Events section, the following error occurs when creating a stack:

> Resource limit exceeded. (Service: AWSLogs; Status Code: 400; Error Code: LimitExceededException; Request ID: 565efb75-522a-11e9-a6c3-61534eead0f1)

I think that it is necessary to have an implementation that causes an error by Linter when LogGroup is described in duplicate.

**Comment by kddejong** [comment]
@chuckmeyer and @rjlohan is this the same idea of the route table association to subnet check we have?
