### ISSUE TITLE
Install fails with aws-sam-translator error

### ISSUE THREAD

**Issue by danhermle** [aws-cloudformation/cfn-python-lint#784]
*cfn-lint version: latest*

*Install fails with aws-sam-translator error*

Collecting aws-sam-translator>=1.9.0 (from cfn-lint)
  Using cached https://files.pythonhosted.org/packages/3d/6c/9ae54e75977fe6284723af19b4c5ef8ef48fac2263d5808f2d091f5adcf6/aws-sam-translator-1.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    c:\program files (x86)\python35-32\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in aws-sam-translator setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in enum34~=1.1; python_version<"3.4" at ; python_version<"3.4"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\dhermle\AppData\Local\Temp\pip-install-76adngxs\aws-sam-translator\

Installing on windows with Python 3.7 installed.  Fails using pip and manual install from downloaded files.

**Comment by kddejong** [comment]
What version were you upgrading from or is this a fresh install?  Also can you tell me what version of setuptools you have from pip?

**Comment by danhermle** [comment]
Thanks for the nudge in the right direction.  Running "pip install --upgrade setuptools" allowed me to successfully complete the install.
