### ISSUE TITLE
Add length checking to IAM ManagedPolicy resource types

### ISSUE THREAD

**Issue by cervantek** [aws-cloudformation/cfn-python-lint#808]
The PolicyDocument specified in an IAM Managed Policy has a maximum length of 6,144 characters (after converted to JSON and minified).
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html

Could a new check be added that converts the PolicyDocument portion of ManagedPolicy resources from YAML to JSON, minifies it, and checks its length?

There are other limits on in-line policies, and they vary depending on what type of resource they are specified in. It would be ideal to have the above type of length checking for all of them, but for me, ManagedPolicy is the most important. This is due to Managed Policies being used as Permissions Boundaries, which can be quite long.

**Comment by kddejong** [comment]
Absolutely.  We just built a similar rule for the Assume Role Policy Document and I don't see why we can't do it here.
