### ISSUE TITLE
E3001 AWS::Greengrass::ResourceDefinition Invalid resource

### ISSUE THREAD

**Issue by mneil** [aws-cloudformation/cfn-python-lint#827]
*cfn-lint version: 0.18.1*

*E3001 on AWS::Greengrass::ResourceDefinition*

The type AWS::Greengrass::ResourceDefinition is giving an E3001 error.

This is a newer / valid resource https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-greengrass-resourcedefinition.html

**Comment by kddejong** [comment]
@rjlohan quick review for this one.  `AWS::Greengrass::ResourceDefinition` isn't in the spec but things like `AWS::Greengrass::ResourceDefinitionVersion` are.  We can patch it of course but seems like something is missing here and we should be able to get this fixed on our side without patching.  Wouldn't you agree?

**Comment by kddejong** [comment]
Fixed with release v0.20.0
