### ISSUE TITLE
Support resource metadata for ignoring checks

### ISSUE THREAD

**Issue by atkinsonm** [aws-cloudformation/cfn-python-lint#835]
*cfn-lint version: any*

*Description of issue.*

This is a feature request for using the metadata section of resources. Declaring `ignore_checks` at the resource level would allow for ignoring a specific instance of a check while keeping that check active for the rest of a template.

Possibly related: #113

**Comment by kddejong** [comment]
I think this is the first iteration to #113.  Let me look into what it will take to get this done.

**Comment by atkinsonm** [comment]
Thanks! Happy to contribute where I can.

**Comment by atkinsonm** [comment]
Great work @kddejong and @cmmeyer! Looking forward to this!
