### ISSUE TITLE
E3001 AWS::EC2::VPCEndpointService Invalid resource in us-west-2

### ISSUE THREAD

**Issue by kmoschkau** [aws-cloudformation/cfn-python-lint#843]
cfn-lint version: 0.18.1

E3001 on AWS::EC2::VPCEndpointService in us-west-2

The type AWS::EC2::VPCEndpointService is giving an E3001 error.

This is a newer / valid resource https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html
But I could not find it in the spec.

**Comment by kddejong** [comment]
The only spec that I'm finding this in is eu-north-1 which is interesting.

We can patch this as a short term fix but we'll need to dig into why this isn't the actual spec file.

Thanks for providing this feedback.

**Comment by kddejong** [comment]
Fixed with release v0.20.0
