### ISSUE TITLE
cfn-lint doesn't identify AWS::NotificationARNs as a list

### ISSUE THREAD

**Issue by eddieramirez** [aws-cloudformation/cfn-python-lint#848]
*cfn-lint version: `cfn-lint 0.19.1`*

*Description of issue*
Pseudo Parameter `AWS::NotificationARNs` returns a list, yet cfn-lint identifies it as a string.

**AWS::NotificationARNs**
>Returns the list of notification Amazon Resource Names (ARNs) for the current stack.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-notificationarns

**Comment by kddejong** [comment]
Fixed with release v0.20.0
