### ISSUE TITLE
E0001 Error transforming template: unhashable type: 'dict_node'

### ISSUE THREAD

**Issue by AZ1904** [aws-cloudformation/cfn-python-lint#856]
*cfn-lint version: 0.19.1*

*cfn-lint crashes with an exception.*

Cfn-lint crashes with an exception. Here's the stack trace:

```
cfn-lint -t "C:\......\template.yaml"
ERROR:root:Plugin 'ImplicitApiPlugin' raised an exception: unhashable type: 'dict_node'
Traceback (most recent call last):
  File "C:\Users\ABC\AppData\Roaming\Python\Python36\site-packages\samtranslator\plugins\__init__.py", line 130, in act
    getattr(plugin, method_name)(*args, **kwargs)
  File "C:\Users\ABC\AppData\Roaming\Python\Python36\site-packages\samtranslator\plugins\api\implicit_api_plugin.py", line 78, in on_before_transform_template
    self._process_api_events(function, api_events, template, condition)
  File "C:\Users\ABC\AppData\Roaming\Python\Python36\site-packages\samtranslator\plugins\api\implicit_api_plugin.py", line 141, in _process_api_events
    api_dict = self.api_conditions.setdefault(api_id, {})
TypeError: unhashable type: 'dict_node'
E0001 Error transforming template: unhashable type: 'dict_node'
C:\......\template.yaml:1:1
```

I'm using the latest version of the app plus i have used the cfn-lint -u command to update the specs. The problem persists.

I can't figure out which part of the template is causing this. I am using nested templates by the way and the child template is in a separate file on the same dir. Linting the child template works fine.

**Comment by kddejong** [comment]
Interesting.  That is on the sam translator package.  Are you able to run `sam translate` on that file?

**Comment by AZ1904** [comment]
Nevermind, I don't think this is a cfn-lint issue as i get the same exception from samtranslator. I've opened up an issue[ here](https://github.com/awslabs/serverless-application-model/issues/907), in case you are interested.
