### ISSUE TITLE
License file not included in distribution

### ISSUE THREAD

**Issue by hajapy** [aws-cloudformation/cfn-python-lint#878]
*cfn-lint version: 0.20.1*

*Description of issue.*
The LICENSE file is not included in the source distribution uploaded to pypi (eg. download the source file https://pypi.org/project/cfn-lint/0.20.1/#files). This causes issues for downstream packagers (I am trying to make this available in conda-forge: https://github.com/conda-forge/staged-recipes/pull/8325). Please consider including this in the MANIFEST.in file.

**Comment by kddejong** [comment]
Absolutely. Sorry about that. We will look into this or you can submit a pull request.
