### ISSUE TITLE
Add support for Node.js v10.x

### ISSUE THREAD

**Issue by devhops** [aws-cloudformation/cfn-python-lint#896]
`cfn-lint --version cfn-lint 0.20.1`

*Description of issue.*

AWS has added support for nodejs 10.x to Lambda. However this will generate an error using cfn-lint as it does not support this yet.

https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10 

Create a template for lambda in cloudformation and add `Runtime: nodejs10.x` then run `cfn-lint` against that template.

``` 
E3030 You must specify a valid value for Runtime (nodejs10.x).
Valid values are ['dotnetcore1.0', 'dotnetcore2.0', 'dotnetcore2.1', 'go1.x', 'java8', 'nodejs', 'nodejs4.3-edge', 'nodejs4.3', 'nodejs6.10', 'nodejs8.10', 'provided', 'python2.7', 'python3.6', 'python3.7', 'ruby2.5']
mytemplate.yaml:14:7 
```

Running `cfn-lint -u` and updating to the latest version does not resolve the issue.

**Comment by fatbasstard** [comment]
Hi @devhops,

We've added this yesterday (https://github.com/aws-cloudformation/cfn-python-lint/pull/890) so it will be available in the next release (coming soon)

**Comment by devhops** [comment]
Thanks!
