### ISSUE TITLE
Double in mapping thrown E7001 error

### ISSUE THREAD

**Issue by KenHundley** [aws-cloudformation/cfn-python-lint#901]
*cfn-lint version: cfn-lint 0.20.1*

*Description of issue.*
When a mapping value is a double (ex. 1.1) it returns the error `E7001:Mapping [map] has invalid property at [property]`

Examples:
With double value:
![image](https://user-images.githubusercontent.com/2495780/57731384-887bc580-7668-11e9-998c-f983a1029716.png)

Changed to Int:
![image](https://user-images.githubusercontent.com/2495780/57731469-b19c5600-7668-11e9-9521-20eadd2885a4.png)

Example CFT: [environment.yaml.txt](https://github.com/aws-cloudformation/cfn-python-lint/files/3179852/environment.yaml.txt)

**Comment by kddejong** [comment]
Thanks. I’ll take a look
