### ISSUE TITLE
Description of cfn-lint development environment and build steps

### ISSUE THREAD

**Issue by matsev** [aws-cloudformation/cfn-python-lint#903]
*cfn-lint version:*
cfn-lint 0.20.1

*Description of issue.*

In the [Contributing via Pull Requests](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CONTRIBUTING.md#contributing-via-pull-requests) paragraph, it is stated that 

> 3. Ensure local tests pass.

However, neither in the [CONTRIBUTING.md](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CONTRIBUTING.md) nor in the [README.md](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/README.md) document is it described how one can setup the cfn-lint development environment and execute these tests.

**Comment by fatbasstard** [comment]
Yeah, you're completely right, the development setup is not really described.
We'll make sure this is (better) documented. 

Do you need any help or got a specific question right now @matsev ?

**Comment by matsev** [comment]
@fatbasstard My intention was to setup the build environment and play with it to get a better understanding of the linter and CloudFormation, however I got stuck before I started. I have only some Python experience and last time I tried I spent a lot of time struggling with installing runtime versions, dependency management (pip, anaconda, virtualenv) and so on before I could do anything useful. I suggest that you add a few lines about required runtime, tools (if any, preferably with a link to each homepage respectively), environment config etc to your documentation.

**Comment by PatMyron** [comment]
Biggest thing that helped me was realizing local repositories can be installed using:
`pip install -e .`

**Comment by PatMyron** [comment]
**At least one of these properties must be specified:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/b788cc9bd3d49ed20d5f2e58602755a0ef37f52c/src/cfnlint/data/AdditionalSpecs/AtLeastOne.json#L20-L25

**Only one of these properties may be specified:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/b788cc9bd3d49ed20d5f2e58602755a0ef37f52c/src/cfnlint/data/AdditionalSpecs/OnlyOne.json#L79-L84

**If this property (`SnapshotIdentifier`) is specified, these properties must be excluded:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/b788cc9bd3d49ed20d5f2e58602755a0ef37f52c/src/cfnlint/data/AdditionalSpecs/Exclusive.json#L102-L107

**If this property (`VpcId`) is specified, these properties must be included:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/b788cc9bd3d49ed20d5f2e58602755a0ef37f52c/src/cfnlint/data/AdditionalSpecs/Inclusive.json#L48-L52

---

**Allowed patterns:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/a46773c752247c51effef415bd3462eaec10ab0b/src/cfnlint/data/ExtendedSpecs/all/03_value_types.json#L33-L36

**Allowed values:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/6cce9222c89056f1546f6fee068ce6dc9dfa394e/src/cfnlint/data/ExtendedSpecs/all/03_value_types/aws_codebuild.json#L2-L11

**List size constraints:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/6cce9222c89056f1546f6fee068ce6dc9dfa394e/src/cfnlint/data/ExtendedSpecs/all/03_value_types/aws_iam.json#L71-L78

**Number size constraints:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/df8d065380e49e53dad9513dab41c2438e105f43/src/cfnlint/data/ExtendedSpecs/all/03_value_types/aws_sqs.json#L17-L24

**String size constraints:**
https://github.com/aws-cloudformation/cfn-python-lint/blob/67fc5bb210b020e3226261f966a01726d574475d/src/cfnlint/data/ExtendedSpecs/all/03_value_types/aws_logs.json#L2-L9

---

There should be no functional difference, but [`src/cfnlint/data/ExtendedSpecs/all/03_value_types`](https://github.com/aws-cloudformation/cfn-python-lint/tree/master/src/cfnlint/data/ExtendedSpecs/all/03_value_types) and [`src/cfnlint/data/ExtendedSpecs/all/04_property_values`](https://github.com/aws-cloudformation/cfn-python-lint/tree/master/src/cfnlint/data/ExtendedSpecs/all/04_property_values) are more organized than [`src/cfnlint/data/ExtendedSpecs/all/03_value_types.json`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/data/ExtendedSpecs/all/03_value_types.json) and [`src/cfnlint/data/ExtendedSpecs/all/04_property_values.json`](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/data/ExtendedSpecs/all/04_property_values.json), so they should be preferred locations for new constraints 

---

After editing these files, the rest of the necessary changes should be auto-generatable by running:

```shell
cfn-python-lint $ pip3 install -e . --user
cfn-python-lint $ cfn-lint --update-specs
```

**Comment by miparnisari** [comment]
> In the [Contributing via Pull Requests](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CONTRIBUTING.md#contributing-via-pull-requests) paragraph, it is stated that "Ensure local tests pass." 
> However, neither in the [CONTRIBUTING.md](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CONTRIBUTING.md) nor in the [README.md](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/README.md) document is it described how one can setup the cfn-lint development environment and execute these tests.

This is now documented here: https://github.com/aws-cloudformation/cfn-python-lint/blob/master/CONTRIBUTING.md#development-environment

Resolving :)
