### ISSUE TITLE
Prefer Fn::Sub over Fn::Join for simple substitution

### ISSUE THREAD

**Issue by atkinsonm** [aws-cloudformation/cfn-python-lint#917]
*cfn-lint version: (`cfn-lint --version`)* 0.20.1

*Description of issue.*

`!Sub` is generally more readable than `!Join` for simple substitution. A common design pattern is to use `!Join` with an empty string delimiter `''`. `!Sub` can accomplish this same function but is often easier to read which aids others in interpreting a template. There are other cases but empty string is the most obvious.

**Comment by direvus** [comment]
I totally agree with you about Sub vs Join, but this proposed rule would be quite opinionated.  Maybe put it at INFO level, or make it opt-in?

**Comment by atkinsonm** [comment]
Agreed, this would be info level.
