### ISSUE TITLE
iam policy statement can only contain one colon

### ISSUE THREAD

**Issue by daisuke-awaji** [aws-cloudformation/cfn-python-lint#935]
*cfn-lint version: (`cfn-lint --version`)*

*Description of issue.*

```
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "iamrole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "iampolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - "cloudwatch:*"
                  - "ec2:ec2:CreateNetworkInterface"←wrong
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DeleteNetworkInterface"
                Resource: "*"
```

The following error occurs when deploying using this template.

```
Actions/Condition can contain only one colon. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 751c17bd-199d-453a-a08f-40f8c5b251a9)
```

It may be difficult to check all of iam's policies, but it may be possible to detect grammatical errors, such as the absence of multiple colons.

**Comment by daisuke-awaji** [comment]
It may be difficult to check all of iam's policies, but it may be possible to detect grammatical errors, such as the absence of multiple colons.

**Comment by kddejong** [comment]
So we have an experimental rule that was supposed to check for this stuff.  It was experimental cause there was some concerns about the source of the permissions.  In your case the resource wasn't covered so this was updated to include more resource types.

**Comment by kddejong** [comment]
Example to use experimental rules is `cfn-lint --include-experimental test/fixtures/templates/quickstart/nist_iam.yaml` 

I would love some testing here (if you could help) because I would love to make this a regular rule.
