### ISSUE TITLE
W2507 "Security Group Id Parameter should of type" invalid for cross-account references

### ISSUE THREAD

**Issue by direvus** [aws-cloudformation/cfn-python-lint#960]
*cfn-lint version: (`cfn-lint --version`)*

cfn-lint 0.21.4

*Description of issue.*

The warning W2507 "Security Group Id Parameter should be of type [AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>, AWS::EC2::SecurityGroup::Id]" is appearing against my template, where I use parameters to take the IDs of Security Groups in other accounts.

These cross-account SG ID references work perfectly well in the SourceSecurityGroupId property of SecurityGroupIngress, when paired with a SourceSecurityGroupOwnerId.

The suggestion from the cfn-lint warning is to use the special parameter type for SG IDs, but this won't work as it will validate the input against the list of security groups in the *same* account.  Cross-account references will be rejected as invalid, even though they are completely valid when used in the actual resource properties.

I'm not sure what the proper solution is here, but in the worst case maybe we just have to concede the reality that "String" is a possible valid data type for security group IDs.

**Comment by kddejong** [comment]
So this was an early rule.  I'm proposing we remove this rule, make it more lenient (accepting strings) with the spec patching definitions we have.  

The other part of this rule is it was written before we had `Info` level errors and I don't think we would have written this as a `Warning`.  Giving more credibility to just removing it.

**Comment by direvus** [comment]
Nice, thanks @kddejong !
