### ISSUE TITLE
Color output in the terminal

### ISSUE THREAD

**Issue by direvus** [aws-cloudformation/cfn-python-lint#971]
*cfn-lint version: (`cfn-lint --version`)*

cfn-lint 0.21.5

*Description of issue.*

Colourising the output of cfn-lint in the terminal would be a real advantage for readability.

Output in the style of [ack](https://beyondgrep.com/) would be brilliant, we could show the actual lines that were flagged, together with line numbers, maybe some surrounding context.

**Comment by PatMyron** [comment]
Circling back on this, [the Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint) sorts by rule level with colored icons if anyone is looking for a solution available today
<img width="30" alt="Screen Shot 2019-12-13 at 6 38 47 PM" src="https://user-images.githubusercontent.com/7014355/70842384-d2cc4d00-1dd7-11ea-80ce-9bac8e7a75ec.png">

**Comment by direvus** [comment]
Nice!
