### ISSUE TITLE
0002 Unknown exception while processing rule E1010: too many values to unpack

### ISSUE THREAD

**Issue by mike-rsi** [aws-cloudformation/cfn-python-lint#986]
*cfn-lint version: 0.21.6*

*Description of issue.*

When using the YAML full function name `Fn::GetAtt` in combination with shorthand syntax for the logical resource name and a _multi-part_ attribute name (i.e. contains a `.` separator, e.g. `Endpoint.Address`) cfn-lint returns the following error:
```
0002 Unknown exception while processing rule E1010: too many values to unpack
template.yaml:1:1
```

_CloudFormation sample that generated the issue:_
```
...

Outputs:
  RedshiftClusterEndpointAddress:
    Description: Endpoint address for Redshift cluster.
    Value:
      Fn::GetAtt: RedshiftCluster.Endpoint.Address
```

_Links to the (official) documentation for clarification:_

1. Fn::GetAtt: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
2. Available Redshift Cluster attributes: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#aws-resource-redshift-cluster-return-values

**Comment by kddejong** [comment]
Fixed in #992 and released.
