### ISSUE TITLE
jsonschema dependency unsolvable

### ISSUE THREAD

**Issue by martenjacobs** [aws-cloudformation/cfn-python-lint#988]
There's a dependency issue with `jsonschema`, 

### Steps to reproduce
```bash
mkdir cfn-test && cd cfn-test
cat <<EOF >Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "3.6"

[pipenv]
allow_prereleases = true

[packages]
cfn-lint = "*"
EOF
pipenv install
```

### Expected result
Installation succeeds successfully

### Actual result
Installation fails due to unsolvable dependency:
`ERROR: Could not find a version that matches jsonschema~=2.6,~=3.0`

This is due to the fact that `aws-sam-translator` has changed its dependency on jsonschema from `~2.6` to `~3.0`, starting from version `1.12.0`, while this package still depends on `~2.6`.

### Proposed solution
Pin the dependency for this package to `aws-sam-translator` version 1.11.0 until `jsonschema` 3.0 can be supported

**Comment by yan12125** [comment]
FYI, this is fixed in master: https://github.com/aws-cloudformation/cfn-python-lint/commit/0ff876934e9ed093785876e976fb13b64a1b8eb4

**Comment by martenjacobs** [comment]
Ah right, any idea when we can expect this on Pypi?

**Comment by kddejong** [comment]
Working on it now.

**Comment by kddejong** [comment]
v0.22.0 has been released and is available in pypi
